export { IncomeDataSection } from './IncomeDataSection';
export { SelfFinancingSection } from './SelfFinancingSection';
export { DeviceEstimationSection } from './DeviceEstimationSection';
export { CO2CalculationSection } from './CO2CalculationSection';
export { EWasteSection } from './EWasteSection';
export { PricingModelSection } from './PricingModelSection';
export { DataGapsSection } from './DataGapsSection';
export { IntegrityReportSection } from './IntegrityReportSection';
export { TransparencyPrinciplesSection } from './TransparencyPrinciplesSection';
