/**
 * Core Foundation Data — Original research batch
 *
 * Contains: Priority 1 (Apply Now), Priority 2 (Rolling),
 * Priority 3 (Watch & Wait + ESA Registry), Networks
 */

import type { Foundation } from '../../schemas/foundation';

export const STIFTUNGEN_CORE: Foundation[] = [
  // ---- PRIORITY 1: Apply Now (Deadline in 1-3 months) ----
  {
    slug: 'klimastiftung',
    name: 'Klimastiftung Schweiz',
    type: 'A',
    status: 'open',
    deadline: '2026-03-01',
    // Deep research: 2026-02-09 — low fit (funds tech product innovations, not social enterprises)
    deadlineText: '1. März 2026',
    nextDeadline: '1. September 2026',
    deadlines: [
      { date: '1. März 2026', response: 'Entscheid bis ca. Juni 2026' },
      { date: '1. September 2026', response: 'Entscheid bis ca. November 2026' },
    ],
    responseTime: '~3 Monate',
    decisionCycle: 'Halbjährlich: März → Juni, September → November',
    amount: { min: 5000, max: 200000, text: "bis CHF 200'000 (max. 50% Projektkosten)" },
    fit: 1,
    priority: 3,
    tagline: 'Die Stiftung, die KMUs beim Klimaschutz unterstützt',
    founded: 2008,
    annualBudget: 'ca. CHF 3 Mio.',
    capital: 'Jährlich ca. CHF 3 Mio. (von 33 Partnerunternehmen)',
    region: 'CH/FL',
    applicationUrl: 'https://www.klimastiftung.ch/de/antrag-stellen/',
    websiteUrl: 'https://www.klimastiftung.ch',
    applicationMethod: 'online',
    contact: {
      address: 'Mythenquai 50/60, 8002 Zürich',
      email: 'info@klimastiftung.ch',
      phone: '+41 43 285 44 80',
    },
    purposeSummary: 'Fördert technische Innovationen mit Klimawirkung, die auf Markteinführung abzielen. Seit 2008 über 200 Projekte mit CHF 42 Mio.+ gefördert. Fokus: Neuartige Technologien/Produkte (z.B. Robotik, neue Materialien, Biotech). Ausschlüsse: Kapazitätsaufbau, Bildungsprojekte, Optimierung bestehender Infrastruktur, soziale Unternehmungen ohne technologische Innovation.',
    researchNotes: 'Geringer Fit für Revamp-IT: Die Stiftung fördert explizit technische Produktinnovationen für den Markt, nicht soziale Unternehmen im Bereich Geräteaufbereitung/Refurbishment. Geförderte Projekte sind typischerweise Hardware-Innovationen (Roboter, Materialien, Biotech). Ein Antrag wäre nur sinnvoll, falls Revamp-IT ein neuartiges technisches Produkt entwickelt (z.B. KI-gestützte Diagnose-Software für Geräte-Triage). Reines Refurbishment-Modell passt nicht in das Förderschema.',
    applicationProcess: [
      'Im Förderportal registrieren (klimastiftung.ch)',
      'Gesuch bis Stichtag (1. März oder 1. September) einreichen',
      'Prüfung durch Beirat',
      'Entscheid durch Stiftungsrat (ca. 3 Monate nach Deadline)',
    ],
    sourceLinks: [
      { source: 'website', url: 'https://www.klimastiftung.ch/de/antrag-stellen/', label: 'Antragsdetails & Förderkriterien' },
      { source: 'website', url: 'https://www.klimastiftung.ch/de/gefoerderte-projekte/', label: 'Geförderte Projekte (Referenz)' },
    ],
    themes: ['klima', 'kreislaufwirtschaft'],
    source: 'manual',
    researchDate: '2026-02-09',
    needsResearch: false,
    // Registry-level data (2026-02-10)
    grantExpenditure: 'ca. CHF 2.2 Mio./Jahr (2024: 16 Projekte)',
    boardMembers: [
      { name: 'Thomas Hügli', role: 'Präsident' },
      { name: 'Ursula Finsterwald', role: 'Vizepräsidentin' },
      { name: 'Vincent Eckert', role: 'Geschäftsführer' },
      { name: 'Roger Vogel', role: 'Stv. Geschäftsführer' },
      { name: 'Christian Schilz', role: 'Mitglied' },
      { name: 'Daniel Wild', role: 'Mitglied' },
      { name: 'Christian Hofer', role: 'Mitglied' },
    ],
    pastGrantees: ['Borobotics GmbH', 'HILLBOT GmbH', 'Novaris AG', 'Pantec Biosolutions AG', 'RedElec Technologie SA'],
    supervisoryAuthority: 'Eidg. Departement des Innern',
  },
  {
    slug: 'ernst-goehner',
    name: 'Ernst G\u00F6hner Stiftung',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Min. 4 Monate vor Projektstart',
    amount: { min: 15000, max: 30000, text: "CHF 15'000 - 30'000 (typisch)" },
    fit: 3,
    priority: 1,
    tagline: 'Eine der gr\u00F6ssten Schweizer Stiftungen',
    founded: 1957,
    annualBudget: 'ca. CHF 40 Mio.',
    region: 'Schweiz',
    applicationUrl: 'https://ernst-goehner-stiftung.ch/index.php/de/services/Downloads',
    websiteUrl: 'https://ernst-goehner-stiftung.ch',
    applicationMethod: 'post',
    contact: {
      address: 'Ernst G\u00F6hner Stiftung, Artherstrasse 19, 6300 Zug',
      email: 'info@ernst-goehner-stiftung.ch',
      phone: '+41 41 729 66 33',
    },
    purposeSummary: 'Eine der grössten Schweizer Förderstiftungen (gegr. 1957). Fördert gemeinnützige Projekte in Soziales, Bildung, Kultur, Umwelt und Wissenschaft. Unterstützt keine öffentlichen Kernaufgaben. Bewerbung nur per Post.',
    sourceLinks: [
      { source: 'website', url: 'https://ernst-goehner-stiftung.ch/index.php/de/services/Downloads', label: 'Gesuchsunterlagen & Richtlinien' },
    ],
    themes: ['soziale-integration', 'digitale-bildung', 'klima'],
    source: 'manual',
    researchDate: '2026-02-09',
    researchNotes: 'Bewerbungen nur per Post (keine elektronische Einreichung). Neue Richtlinien veröffentlicht — Website prüfen. Derzeit sehr hohes Aufkommen an Gesuchen mit Verzögerungen bei Bestätigungen. Mindestens 4 Monate vor Projektrealisierung einreichen. Massenaussendungen werden nicht beantwortet. Erfordert komplettes Dossier: Antragsformular, Organisationsdetails, Steuerbefreiungsstatus, aktuelle Finanzen, Projektbeschreibung, Budget, Finanzierungsplan. NICHT für öffentliche Kernaufgaben.',
    needsResearch: false,
    // Registry-level data (2026-02-10)
    capital: 'ca. CHF 7.45 Mrd. (inkl. Beteiligungen)',
    grantExpenditure: 'CHF 53.1 Mio. (2024, 1\'929 Projekte)',
    boardMembers: [
      { name: 'Dr. Beat Walti', role: 'Präsident' },
      { name: 'Dr. Roger Schmid', role: 'Vizepräsident' },
      { name: 'Samuel Bon', role: 'Geschäftsführer' },
      { name: 'Daniel Hübscher', role: 'Mitglied' },
      { name: 'Dr. Suzanne Avedik', role: 'Mitglied' },
      { name: 'Giacomo Balzarini', role: 'Mitglied' },
      { name: 'Isabel Kühnlein Specker', role: 'Mitglied' },
      { name: 'Prof. Dr. Michael Hengartner', role: 'Mitglied' },
    ],
    pastGrantees: ['Fondazione Ticino Musica', 'Beyeler-Stiftung', 'Schweizerische Studienstiftung'],
    supervisoryAuthority: 'Zentralschweizer BVG- und Stiftungsaufsicht (ZBSA)',
    memberships: ['SwissFoundations'],
  },
  {
    slug: 'binding',
    name: 'Sophie und Karl Binding Stiftung',
    type: 'A',
    status: 'open',
    deadline: '2026-03-31',
    deadlineText: '31. März 2026 (Antwort Ende Juni). Weitere: 30. Juni, 22. September, 15. Dezember 2026.',
    deadlines: [
      { date: '31. M\u00E4rz', response: 'Ende Juni' },
      { date: '30. Juni', response: 'Ende September' },
      { date: '22. September', response: 'Ende Dezember' },
      { date: '15. Dezember', response: 'Ende M\u00E4rz 2027' },
    ],
    amount: { min: 3000, max: 100000, text: "CHF 3'000 - 100'000+/Jahr" },
    fit: 3,
    priority: 1,
    tagline: 'Grosse Basler Stiftung mit Herz f\u00FCr Jugendintegration',
    region: 'Schweiz',
    applicationUrl: 'https://request-binding.alphafoundation.app',
    websiteUrl: 'https://www.binding-stiftung.ch',
    applicationMethod: 'online',
    contact: {
      email: 'contact@binding-stiftung.ch',
      phone: '+41 61 317 40 90',
    },
    purposeSummary: 'Grosse Basler Stiftung mit Fokus auf Kinder & Jugend (Ausbildungs-/Berufsübergänge), Gesellschaftlicher Zusammenhalt (demokratische Teilhabe, kulturelle Vielfalt), Umwelt und Kultur. Vier Einreichfenster pro Jahr.',
    sourceLinks: [
      { source: 'website', url: 'https://request-binding.alphafoundation.app', label: 'Gesuchsportal' },
    ],
    themes: ['jugend', 'soziale-integration', 'arbeitsintegration', 'digitale-bildung'],
    source: 'manual',
    researchDate: '2026-02-09',
    researchNotes: 'Frist 31. März 2026 BESTÄTIGT. Vier Einreichfenster pro Jahr. Neu ausschliesslich elektronische Einreichung — kein Papier mehr. Relevante Bereiche: \'Kinder & Jugend\' (Ausbildungs-/Berufsübergänge), \'Gesellschaftlicher Zusammenhalt\' (demokratische Teilhabe, kulturelle Vielfalt). Vorgespräch empfohlen für unsichere Projekte: contact@binding-stiftung.ch oder 061 317 40 90.',
    needsResearch: false,
    // Registry-level data (2026-02-10)
    founded: 1963,
    capital: 'ca. CHF 150 Mio.',
    grantExpenditure: 'CHF 3.2 Mio. (2024, kumuliert CHF 99 Mio.+ seit 1963)',
    boardMembers: [
      { name: 'Dr. Thomas Weibel Grob', role: 'Präsident' },
      { name: 'Dr. Carl Binding', role: 'Vizepräsident' },
      { name: 'Monika Wirth', role: 'Geschäftsführerin' },
      { name: 'Sarah Aude Girard', role: 'Mitglied' },
      { name: 'Lena Wunderlin', role: 'Mitglied' },
      { name: 'Tamara von Büren', role: 'Mitglied' },
      { name: 'Dr. Irmgard Maria Wirtz Eybl', role: 'Mitglied' },
    ],
    pastGrantees: ['Verein SPORTEGRATION', 'Swiss Academy for Development (SA4D)', 'Stiftung Ferien im Baudenkmal', 'MindMatters', 'DreamTeam'],
    supervisoryAuthority: 'Eidg. Departement des Innern',
    memberships: ['SwissFoundations', 'proFonds'],
  },
  {
    slug: 'baugarten',
    name: 'Stiftung Baugarten Z\u00FCrich',
    type: 'B',
    status: 'open',
    deadline: '2026-05-01',
    deadlineText: 'Session II: 1. Mai 2026 (Entscheid Mitte Juli). Session III: 1. September 2026 (Entscheid Anfang November).',
    amount: { min: 5000, max: 50000, text: "CHF 5'000 - 50'000" },
    fit: 3,
    priority: 1,
    tagline: 'Z\u00FCrcher Stiftung f\u00FCr soziale & \u00F6kologische Projekte',
    region: 'Stadt & Kanton Z\u00FCrich',
    applicationUrl: 'https://www.baugarten-zuerich.ch/gesuch',
    websiteUrl: 'https://www.baugarten-zuerich.ch',
    applicationMethod: 'online',
    sourceLinks: [
      { source: 'website', url: 'https://www.baugarten-zuerich.ch/gesuch', label: 'Gesuchsdetails' },
    ],
    purposeSummary: 'Zürcher Stiftung, die gemeinnützige Projekte in den Bereichen Soziales, Ökologie, Bildung und Kultur fördert. Drei Eingabefristen pro Jahr (Januar, Mai, September). Nur steuerbefreite Organisationen im Raum Zürich. CHF 5\'000-50\'000 pro Projekt.',
    themes: ['zuerich', 'soziale-integration', 'klima', 'digitale-bildung'],
    source: 'manual',
    researchDate: '2026-02-09',
    researchNotes: 'Frist 1. Mai 2026 BESTÄTIGT (Session II). Drei Sitzungen jährlich: I bis 15. Jan (Entscheid Woche 12), II bis 1. Mai (Woche 28), III bis 1. Sep (Woche 45). 5-Schritte-Verfahren: Online-Vorprüfung, Zulassung, Vollständige Unterlagen, Schriftlicher Entscheid, Auszahlung. AUSGESCHLOSSEN: Festivals, Aufführungen, Veranstaltungen, Publikationen, kommerzielle Vorhaben, Betriebskosten, Einzelpersonen. Nur gemeinnützige steuerbefreite Organisationen in Zürich. Kontakt: info@baugarten-zuerich.ch, +41 44 212 20 88.',
    contact: {
      address: 'Fraumünsterstrasse 19, 8001 Zürich',
      email: 'info@baugarten-zuerich.ch',
      phone: '+41 44 212 20 88',
    },
    needsResearch: false,
    // Registry-level data (2026-02-10)
    capital: 'ca. CHF 400 Mio. (geschätzt)',
    grantExpenditure: 'ca. CHF 5 Mio./Jahr (kumuliert CHF 177 Mio. bis 2024)',
    boardMembers: [
      { name: 'Hans G. Syz', role: 'Präsident' },
      { name: 'Dr. Claude A. Lambert', role: 'Vizepräsident' },
      { name: 'Kaspar Ernst Anton Wenger', role: 'Direktor' },
      { name: 'Dr. Matthias Stephan von Orelli', role: 'Direktor' },
      { name: 'Annemarie Homberger-Rahn', role: 'Mitglied' },
      { name: 'Christopher Oechsle', role: 'Mitglied' },
      { name: 'Ana Patricia Rahn Erden', role: 'Mitglied' },
      { name: 'Ursula Altorfer', role: 'Mitglied' },
    ],
    pastGrantees: ['Verein Appisberg', 'Verein Inselhof Triemli', 'Institut Kinderseele Schweiz', 'Stiftung Arbeitskette', 'Brunau-Stiftung'],
    supervisoryAuthority: 'BVG- und Stiftungsaufsicht des Kantons Zürich (BVS)',
  },

  // ---- PRIORITY 2: Rolling Applications ----
  {
    slug: 'mercator',
    name: 'Mercator Stiftung Schweiz',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Laufend über Online-Portal. Stiftungsrat entscheidet 4x/Jahr (über CHF 100k), 8x/Jahr (CHF 50-100k), vereinfacht (unter CHF 50k). Erste Antwort innert 4 Wochen.',
    responseTime: '4 Wochen (Erstpr\u00FCfung)',
    decisionCycle: 'Board 4x/Jahr (\u00FCber CHF 100k), 8x/Jahr (CHF 50-100k)',
    amount: { min: 30000, max: 400000, text: "CHF 30'000+ (unter 30k: Skizze gen\u00FCgt, dar\u00FCber: Vollantrag)" },
    fit: 3,
    priority: 1,
    tagline: 'Digitalisierung + Gesellschaft: Grundrechte im digitalen Raum',
    founded: 1998,
    region: 'Schweiz',
    applicationUrl: 'https://gesuch.stiftung-mercator.ch',
    websiteUrl: 'https://www.stiftung-mercator.ch',
    applicationMethod: 'online',
    contact: {
      address: 'Gartenstrasse 33, 8002 Z\u00FCrich',
      email: 'info@stiftung-mercator.ch',
      phone: '+41 44 206 55 80',
    },
    uid: 'CHE-109.528.408',
    purposeSummary: 'Sechs Fokusthemen: Demokratie, Diversität, Klima, Digitalisierung, Gesellschaft, Lernen der Zukunft. Besonders relevant: "Digitale Suffizienz" (ressourceneffiziente Nutzung digitaler Technologien, Kreislaufwirtschaft via ICT), gemeinwohlorientierte Digitalisierung, Grundrechte im digitalen Raum. Strategie bis Ende 2025, neue Periode ab 2026.',
    applicationProcess: [
      'Projektskizze \u00FCber gesuch.stiftung-mercator.ch einreichen',
      'Erstpr\u00FCfung innerhalb von 4 Wochen',
      'Bei positivem Bescheid: Einladung zum Vollantrag',
      'Board entscheidet je nach Betrag 4-8x pro Jahr',
    ],
    sourceLinks: [
      { source: 'website', url: 'https://www.stiftung-mercator.ch/stiftung/digitalisierung-gesellschaft', label: 'Digitalisierung & Gesellschaft' },
      { source: 'stiftungschweiz', url: 'https://stiftungen.stiftungschweiz.ch/organisation/stiftung-mercator-schweiz', label: 'StiftungSchweiz-Profil' },
    ],
    themes: ['digitale-bildung', 'digitale-souveraenitaet', 'kreislaufwirtschaft', 'klima'],
    source: 'manual',
    researchDate: '2026-02-09',
    researchNotes: 'Neue Strategieperiode mit sechs Themen: Demokratie, Diversität, Klima, Digitalisierung+Gesellschaft, Lernen der Zukunft, Kunst.Kultur.Transformation. Für Revamp-IT relevant: \'Digitalisierung + Gesellschaft\' und \'Lernen der Zukunft.\' Stiftung fördert neu \'Ökosysteme\' statt nur Einzelprojekte. Projektskizzen über Online-Portal: gesuch.stiftung-mercator.ch. Kontakt: Gartenstrasse 33, 8002 Zürich, +41 44 206 55 80, info@stiftung-mercator.ch.',
    needsResearch: false,
    // Registry-level data (2026-02-10)
    capital: 'ca. CHF 151 Mio. (2024)',
    grantExpenditure: 'CHF 14 Mio. (2024)',
    boardMembers: [
      { name: 'Dr. Annegret Reisner', role: 'Präsidentin' },
      { name: 'Dr. Thomas Hodel', role: 'Vizepräsident' },
      { name: 'Dr. Andrew Nicholas Holland', role: 'Geschäftsführer' },
      { name: 'Katharina Weibel Fischli', role: 'Geschäftsführerin' },
      { name: 'Christian Müller', role: 'Mitglied' },
      { name: 'Claudia Binder Signer', role: 'Mitglied' },
      { name: 'Prof. Dr. Pasqua Perrig-Chiello', role: 'Mitglied' },
      { name: 'Stefan Tieben', role: 'Mitglied' },
    ],
    pastGrantees: ['Dachverband Schweizer Jugendparlamente (DSJ)', 'alliance F', 'Stiftung für Konsumentenschutz', 'Citizen Science Center Zürich'],
    supervisoryAuthority: 'Eidg. Departement des Innern',
    memberships: ['SwissFoundations'],
  },
  {
    slug: 'hirschmann',
    name: 'Hirschmann Stiftung',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Keine festen Fristen. Vorstand entscheidet 3x/Jahr (Frühling, Sommer, Winter). Gesuch mind. 6 Monate vor Projektstart einreichen.',
    decisionCycle: '3x j\u00E4hrlich (Fr\u00FChling/Sommer/Winter)',
    amount: { min: null, max: null, text: 'Variabel (mehrj\u00E4hrig bevorzugt)' },
    fit: 3,
    priority: 2,
    tagline: 'Die Stiftung, die Grassroots-Projekte liebt',
    founded: 1985,
    region: 'Schweiz',
    applicationUrl: 'https://www.hirschmann-stiftung.ch/en/sponsorship/',
    websiteUrl: 'https://www.hirschmann-stiftung.ch',
    applicationMethod: 'email',
    contact: {
      email: 'kontakt@hirschmann-stiftung.ch',
    },
    sdgs: [3, 4, 8],
    sourceLinks: [
      { source: 'website', url: 'https://www.hirschmann-stiftung.ch/en/sponsorship/', label: 'F\u00F6rderrichtlinien' },
    ],
    themes: ['soziale-integration', 'arbeitsintegration', 'digitale-bildung'],
    source: 'manual',
    researchDate: '2026-02-09',
    purposeSummary: 'Fördert gemeinnützige Projekte in Wissenschaft, Bildung, Sozialwesen und Entwicklungszusammenarbeit im Einklang mit SDGs 3, 4 oder 8. Teil des Budgets für Klein-/Impulsprojekte reserviert.',
    researchNotes: 'Bewerbung per E-Mail an kontakt@hirschmann-stiftung.ch mit ausgefülltem Formular + Beilagen. Bestätigung innert 1 Woche. Kein Rechtsanspruch auf Förderung. NICHT gefördert: reine Bauvorhaben, Organisationsunterstützung ohne Projekt, individuelle Stipendien ausserhalb ihrer Programme, kommerzielle Vorhaben, persönliche Schulden.',
    needsResearch: false,
  },
  {
    slug: 'drosos',
    name: 'Drosos Stiftung',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Konzeptnotizen auf Einladung der Stiftung; Spontanbewerbungen werden nur bei Interesse beantwortet.',
    responseTime: '6-12 Monate (inkl. Due Diligence)',
    amount: { min: 50000, max: 500000, text: "CHF 50'000 - 500'000+ (3-5 Jahre)" },
    fit: 2,
    priority: 2,
    tagline: 'Erm\u00F6glicht benachteiligten Menschen, ihr Leben selbst zu gestalten',
    region: 'Z\u00FCrich / Schweiz',
    applicationUrl: 'https://www.drosos.org/how-we-work/partner-us',
    websiteUrl: 'https://www.drosos.org',
    applicationMethod: 'email',
    contact: {
      email: 'info@drosos.org',
    },
    sourceLinks: [
      { source: 'website', url: 'https://www.drosos.org/how-we-work/partner-us', label: 'Partnerschafts-Details' },
    ],
    themes: ['jugend', 'soziale-integration', 'arbeitsintegration'],
    source: 'manual',
    researchDate: '2026-02-09',
    purposeSummary: 'Fördert Kompetenzentwicklung, Unternehmertum und soziale/wirtschaftliche Inklusion für benachteiligte junge Menschen. Aktiv in der Schweiz und 7 weiteren Ländern.',
    researchNotes: 'Schwerpunkte: Kompetenzentwicklung (digitale Kompetenz, kritisches Denken, Anpassungsfähigkeit, Kreativität), Berufsausbildung, Unternehmertum. Zielgruppe: junge Menschen mit sozialen/wirtschaftlichen/persönlichen Nachteilen. Konzeptnotizen auf Einladung — Spontanbewerbungen werden nur bei Interesse beantwortet. Revamp-IT passt gut unter digitale Kompetenzen + Arbeitsintegration für benachteiligte Jugendliche. Sitz in Zürich.',
    needsResearch: false,
    // Registry-level data (2026-02-10)
    capital: 'ca. CHF 800 Mio. (Verbrauchsstiftung)',
    grantExpenditure: 'CHF 18.4 Mio. (2023)',
    boardMembers: [
      { name: 'Markus Emilio Kronauer', role: 'Präsident' },
      { name: 'Edith Monika Kolb', role: 'Vizepräsidentin' },
      { name: 'Suba Umathevan', role: 'Geschäftsführerin' },
      { name: 'Barbara Grünewald', role: 'Mitglied' },
      { name: 'Anton Stadler', role: 'Mitglied' },
      { name: 'Hans Rudolf Castell', role: 'Mitglied' },
    ],
    pastGrantees: ['Fondation IPT', 'Handicap International Suisse', 'Brückensteine Careleaver', 'Lesestark! Dresden'],
    supervisoryAuthority: 'Eidg. Departement des Innern',
    memberships: ['SwissFoundations'],
  },
  {
    slug: 'hasler',
    name: 'Hasler Stiftung',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Laufend für Kleinprojekte (bis CHF 50\'000); Entscheid innert 30 Tagen. Spezielle Programme mit eigenen Fristen.',
    responseTime: '~30 Tage (kleine Projekte)',
    amount: { min: 10000, max: 50000, text: "CHF 10'000 - 50'000+" },
    smallProjects: { max: 10000, text: "bis CHF 10'000 (Events, Publikationen)" },
    fit: 2,
    priority: 2,
    tagline: 'Die ICT-Stiftung der Schweiz seit 1948',
    founded: 1948,
    region: 'Schweiz',
    applicationUrl: 'https://haslerstiftung.ch/en/what-the-hasler-foundation-supports/supportprograms/',
    websiteUrl: 'https://haslerstiftung.ch',
    applicationMethod: 'online',
    sourceLinks: [
      { source: 'website', url: 'https://haslerstiftung.ch/en/what-the-hasler-foundation-supports/supportprograms/', label: 'F\u00F6rderprogramme' },
    ],
    themes: ['digitale-bildung', 'digitale-souveraenitaet', 'jugend'],
    source: 'manual',
    researchDate: '2026-02-09',
    purposeSummary: 'Fördert ICT zum Wohle der Schweiz durch Finanzierung von Bildungs-, Forschungs- und Innovationsprojekten im Bereich Informations- und Kommunikationstechnologien.',
    researchNotes: 'Primär akademisch/forschungsorientiert. Offene Förderung für Universitäten und nicht-kommerzielle Organisationen. Kleinprojekte (bis CHF 50k) ganzjährig mit 30-Tage-Entscheid. Aktuelles Spezialprogramm: \'Hasler Mercator Digitalisierung & Demokratie\' (Start Jan. 2025). Relevanz für Revamp-IT begrenzt — primär akademische Forschung und Uni-Projekte. Könnte unter ICT-Bildung oder digitale Inklusion passen, wenn akademisch gerahmt. NEU: Die Community-Plattform (1\'165 TypeScript-Dateien, Full-Stack Next.js/PostgreSQL) stärkt den Fall für ICT-Bildungsprojekte — beweist Software-Engineering-Kompetenz auf professionellem Niveau.',
    contact: {
      address: 'Hirschengraben 6, 3011 Bern',
      email: 'contact@haslerstiftung.ch',
      phone: '+41 31 381 41 41',
    },
    needsResearch: false,
  },
  {
    slug: 'zkb-philanthropie',
    name: 'ZKB Philanthropie Stiftung',
    type: 'D',
    status: 'closed',
    deadline: null,
    deadlineText: 'Nur auf Einladung — Stiftung identifiziert Projekte proaktiv. Unaufgeforderte Anträge werden NICHT geprüft.',
    amount: { min: null, max: null, text: 'Variabel' },
    fit: 2,
    priority: 2,
    tagline: 'Neue Z\u00FCrcher Stiftung - regional verankert',
    founded: 2024,
    region: 'Kanton Z\u00FCrich',
    applicationUrl: 'https://www.zkb-philanthropie-stiftung.ch/de.html',
    websiteUrl: 'https://www.zkb-philanthropie-stiftung.ch',
    applicationMethod: 'online',
    sourceLinks: [
      { source: 'website', url: 'https://www.zkb-philanthropie-stiftung.ch/de.html', label: 'Stiftungsportrait' },
    ],
    themes: ['zuerich', 'soziale-integration', 'klima', 'digitale-bildung'],
    source: 'manual',
    researchDate: '2026-02-09',
    purposeSummary: 'Unterstützt Projekte mit messbarer Wirkung im Kanton Zürich in den Bereichen Soziales, Kultur, Gesundheit, Bildung, Wissenschaft und Ökologie. Förderstiftung und Dachstiftung.',
    researchNotes: 'WICHTIG: Nur auf Einladung. Unaufgeforderte Anträge werden weder geprüft noch beantwortet. Stiftung sucht aktiv nach passenden Organisationen und kontaktiert diese. Gegründet 2024 als Nachfolgerin früherer ZKB-Wohltätigkeitsaktivitäten. StiftungSchweiz-Profil abonnieren für zukünftige Ausschreibungen.',
    needsResearch: false,
    contact: {
      address: 'c/o ZKB, Bahnhofstrasse 9, 8010 Zürich',
      email: 'Natalie.Joho@zkb.ch',
    },
  },
  {
    slug: 'arbeitsintegration-zh',
    name: 'Arbeitsintegration Z\u00FCrich',
    type: 'D',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Keine feste Frist. Städtisches Partnerschafts-/Programmangebot, kein klassisches Antragsverfahren. Direkt AOZ kontaktieren.',
    amount: { min: null, max: null, text: 'Partnerschaft (Lohnkosten \u00FCbernommen)' },
    fit: 3,
    priority: 2,
    tagline: 'Partnerschaft statt Grant - nachhaltiges Einkommen',
    region: 'Stadt Z\u00FCrich',
    applicationUrl: 'https://www.stadt-zuerich.ch/de/lebenslagen/unterstuetzung-und-beratung/arbeitslosigkeit/arbeitsintegration.html',
    websiteUrl: 'https://www.stadt-zuerich.ch/de/lebenslagen/unterstuetzung-und-beratung/arbeitslosigkeit/arbeitsintegration.html',
    applicationMethod: 'contact',
    isPartnership: true,
    sourceLinks: [
      { source: 'cantonal', url: 'https://www.stadt-zuerich.ch/de/lebenslagen/unterstuetzung-und-beratung/arbeitslosigkeit/arbeitsintegration.html', label: 'Stadt Zürich \u2013 Arbeitsintegration' },
    ],
    themes: ['zuerich', 'arbeitsintegration', 'soziale-integration'],
    source: 'manual',
    researchDate: '2026-02-10',
    purposeSummary: 'AOZ-Arbeitsintegrationsprogramme begleiten Sozialhilfeempfänger zur Arbeitsmarktintegration. Programme umfassen NAVI (4-Wochen-Orientierung), Workshops, Coaching und Garten-/Waldunterhalt. 4 von 10 Teilnehmenden kehren in den primären Arbeitsmarkt zurück.',
    researchNotes: 'KEINE fördernde Stiftung, sondern eine städtische Abteilung (AOZ) mit Integrationsleistungen. Revamp-IT müsste eine Partnerschaft als Programmanbieter oder Platzierungspartner prüfen. AOZ betreibt Programme in verschiedenen Bereichen (Gastronomie, Textil, Logistik). IT-Refurbishment und Linux-Schulungen könnten als neues AOZ-Arbeitsintegrationsprogramm positioniert werden. Stadt Zürich finanziert Programmplätze direkt.',
    needsResearch: false,
    contact: {
      address: 'Zypressenstrasse 60, 8040 Zürich',
      email: 'gep.leitung@aoz.ch',
      phone: '+41 44 415 63 39',
    },
  },
  {
    slug: 'zuerich-jobs',
    name: 'Stiftung Z\u00FCrich-Jobs',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Jederzeit',
    amount: { min: null, max: null, text: 'Variabel' },
    capital: 'CHF 3.4 Mio.',
    fit: 3,
    priority: 2,
    tagline: 'Stadt + Wirtschaft f\u00FCr Jugend-Arbeitsintegration',
    founded: 2006,
    region: 'Stadt Z\u00FCrich',
    applicationUrl: 'https://stiftungzuerichjobs.ch/',
    websiteUrl: 'https://stiftungzuerichjobs.ch/ueber/',
    applicationMethod: 'contact',
    sourceLinks: [
      { source: 'website', url: 'https://stiftungzuerichjobs.ch/ueber/', label: 'Über die Stiftung' },
    ],
    themes: ['zuerich', 'jugend', 'arbeitsintegration'],
    source: 'manual',
    researchDate: '2026-02-10',
    purposeSummary: 'Gemeinsame Initiative von Wirtschaft und Stadt Zürich zur Arbeitsintegration von Sozialhilfeempfängern und Jugendlichen. Unterstützt KMU mit Ressourcen und Expertise für Arbeitsplatzierungen. Stiftungskapital CHF 3.4 Mio., gegründet 2006.',
    researchNotes: 'Kein spezifisches Antrags-/Gesuchverfahren gefunden. Website stiftungzuerichjobs.ch direkt konsultieren. Stiftung unterstützt öffentliche und private Organisationen bei der Arbeitsintegration für Jugendliche/junge Erwachsene und marktorientierte Integration für Sozialhilfeempfänger.',
    needsResearch: false,
    contact: {
      email: 'annemarie.homberger@stiftungzuerichjobs.ch',
    },
  },
  {
    slug: 'max-kohler',
    name: 'Max Kohler Stiftung',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Halbjährlich: Vorstandssitzungen Mai und November. Nächste Frist voraussichtlich ~31. März 2026 (für Mai-Sitzung). Online-Tool auf Website.',
    amount: { min: null, max: null, text: 'Variabel' },
    fit: 2,
    priority: 2,
    tagline: 'Arts for Change - Kreativit\u00E4t f\u00FCr Integration',
    founded: 2003,
    region: 'Z\u00FCrich',
    applicationUrl: 'https://www.maxkohler-stiftung.ch/en/contact/applications/',
    websiteUrl: 'https://www.maxkohler-stiftung.ch',
    applicationMethod: 'email',
    purposeSummary: 'Fördert drei Bereiche: (1) herausragende Ausstellungen/Aufführungen, (2) kulturelle Bildung für Kinder und Jugendliche, (3) Kinderschutz und Integrationsprojekte. Halbjährliche Fristen (Mai und November). Gegründet 2003, Sitz in Zürich.',
    sourceLinks: [
      { source: 'website', url: 'https://www.maxkohler-stiftung.ch/en/contact/applications/', label: 'Bewerbungsrichtlinien' },
    ],
    themes: ['zuerich', 'jugend', 'soziale-integration'],
    source: 'manual',
    researchDate: '2026-02-10',
    researchNotes: 'Drei Förderbereiche: (1) Herausragende Ausstellungen/Aufführungen (proaktiv — keine unaufgeforderten Anträge), (2) Kulturelle Bildung für Kinder/Jugendliche, (3) Kinderschutz und Integrationsprojekte. Online-Tool, zweistufig. Revamp-IT könnte unter Bereich 3 (Integration) passen, wenn auf Jugendliche/Kinder ausgerichtet. 2026-Fristen noch nicht publiziert.',
    needsResearch: false,
    contact: {
      address: 'Schiffländestrasse 5, 8001 Zürich',
      email: 'info@maxkohler-stiftung.ch',
      phone: '+41 43 545 92 04',
    },
  },
  {
    slug: 'glueckskette',
    name: 'Gl\u00FCckskette',
    type: 'A',
    status: 'open',
    deadline: null,
    deadlineText: 'Laufende Projektskizzen per E-Mail an pro-ch@glueckskette.ch. Antwort innert 2-3 Wochen.',
    amount: { min: null, max: null, text: 'Variabel' },
    fit: 2,
    priority: 2,
    tagline: 'Berufliche + Soziale Integration junger Menschen',
    region: 'Schweiz',
    applicationUrl: 'https://www.glueckskette.ch/sammlungen/berufliche-und-soziale-integration-junger-menschen-in-der-schweiz/',
    websiteUrl: 'https://www.glueckskette.ch',
    applicationMethod: 'online',
    sourceLinks: [
      { source: 'website', url: 'https://www.glueckskette.ch/sammlungen/berufliche-und-soziale-integration-junger-menschen-in-der-schweiz/', label: 'Programm: Integration junger Menschen' },
    ],
    themes: ['jugend', 'soziale-integration', 'arbeitsintegration'],
    source: 'manual',
    researchDate: '2026-02-09',
    purposeSummary: 'Unterstützt berufliche und soziale Integration junger Menschen in der Schweiz, die durch das soziale und berufliche Sicherheitsnetz gefallen sind. Stärkt Selbstvertrauen, persönliche/soziale Kompetenzen und Arbeitsmarktfähigkeiten.',
    researchNotes: 'Fokus seit 2025 auf Kinder/Jugend/junge Erwachsene. Hälfte der gesammelten Spenden geht in \'Berufliche und soziale Integration junger Menschen in der Schweiz.\' Max. 4 Jahre Unterstützung, max. CHF 200k/Jahr (abnehmend). Min. CHF 50k Antrag. Ein Antrag pro Organisation pro Schwerpunktthema. Kurze Projektskizze per Formular + Anhang an pro-ch@glueckskette.ch. 2026 ist Planungsjahr für 2027-2031 Prioritäten. Revamp-IT passt STARK: Arbeitsintegration für benachteiligte junge Menschen.',
    needsResearch: false,
    contact: {
      email: 'pro-ch@glueckskette.ch',
    },
  },
  {
    slug: 'minerva',
    name: 'Minerva Stiftung',
    type: 'B',
    status: 'closed',
    deadline: null,
    deadlineText: 'WICHTIG: Bereich Natur (Biodiversität, Kreislaufwirtschaft, nachhaltige Ernährung) nimmt derzeit KEINE Anträge an. Bereich Bildung weiterhin offen mit Quartalsfristen: Feb, Mai, Aug, Okt.',
    decisionCycle: 'M\u00E4rz, Juni, September, November',
    amount: { min: null, max: null, text: 'Variabel' },
    fit: 3,
    priority: 2,
    tagline: 'Kreislaufwirtschaft & Jugendbildung (15-25) aus Lugano',
    founded: null,
    region: 'Schweiz (Fokus auch Tessin)',
    applicationUrl: 'https://minerva-stiftung.org/',
    websiteUrl: 'https://minerva-stiftung.org',
    applicationMethod: 'online',
    contact: {
      address: 'Vicolo Nassetta 2, 6900 Lugano',
      email: 'info@minerva-stiftung.org',
      phone: '+41 79 945 37 38',
    },
    criteria: {
      nature: 'Messbare Projekte mit Skalierungspotenzial, Kreislaufwirtschaft, Ressourcenschonung',
      education: 'Jugendprogramme 15-25, \u00DCbergang Schule-Beruf, hohe Jugendarbeitslosigkeit',
    },
    sourceLinks: [
      { source: 'website', url: 'https://minerva-stiftung.org/', label: 'Stiftungs-Website & F\u00F6rderkriterien' },
    ],
    themes: ['kreislaufwirtschaft', 'jugend', 'soziale-integration', 'arbeitsintegration'],
    source: 'fundraiso',
    researchDate: '2026-02-09',
    purposeSummary: 'Stiftung mit Sitz in Lugano, fördert Projekte in Kreislaufwirtschaft und beruflicher Bildung für Jugendliche (15-25 Jahre). Fokus auf messbare, wirkungsvolle Schweizer Projekte mit Skalierungspotenzial.',
    researchNotes: 'Kreislaufwirtschafts-Anträge GESCHLOSSEN. Bewerbung unter Bildungsfokus weiterhin möglich (Übergang Schule-Lehre, Regionen mit hoher Jugendarbeitslosigkeit). Vorstand entscheidet quartalsweise (März, Juni, Sept., Nov.). Antrag ausschliesslich über Online-Formular, akzeptiert in DE/EN/FR. Kontakt: info@minerva-stiftung.org, +41 79 945 37 38. Adresse: Vicolo Nassetta 2, 6900 Lugano.',
    needsResearch: false,
  },

  // ---- PRIORITY 3: Watch & Wait ----
  {
    slug: 'prototype-fund',
    name: 'Prototype Fund Schweiz',
    type: 'A',
    status: 'soon',
    deadline: null,
    deadlineText: 'Runde 4 Demo Day war 22. Januar 2026. Bewerbungsphase Runde 5 voraussichtlich in Kürze. Noch keine bestätigten Daten für Runde 5 publiziert. Bis CHF 100\'000 pro Projekt.',
    amount: { min: null, max: 100000, text: "bis CHF 100'000 (6 Monate)" },
    fit: 1,
    priority: 1,
    tagline: 'F\u00F6rdert Open-Source-Projekte f\u00FCr das Gemeinwohl',
    region: 'Schweiz',
    applicationUrl: 'https://prototypefund.opendata.ch/bewerbung/',
    websiteUrl: 'https://prototypefund.opendata.ch',
    applicationMethod: 'online',
    requiresOpenSource: true,
    sourceLinks: [
      { source: 'website', url: 'https://prototypefund.opendata.ch/bewerbung/', label: 'Bewerbungsprozess' },
    ],
    themes: ['digitale-souveraenitaet', 'klima', 'kreislaufwirtschaft', 'digitale-bildung'],
    source: 'manual',
    researchDate: '2026-02-19',
    purposeSummary: 'Fördert Open-Source-Projekte, die gesellschaftliche Herausforderungen in der Schweiz adressieren. Fokus auf nachhaltige Digitalisierung und digitale Suffizienz. Eine Runde pro Jahr, bis CHF 100\'000. Schweizer Arbeitsbewilligung erforderlich.',
    researchNotes: 'PERFEKTER FIT: Revamp-ITs Community-Plattform (revampit.vercel.app) ist ein produktionsreifes Open-Source-Projekt mit 1\'165 TypeScript-Dateien, das drei gesellschaftliche Herausforderungen adressiert: (1) Digitale Souveränität — Open-Source-Marktplatz und Wissensplattform, (2) Kreislaufwirtschaft — digitale Infrastruktur für gebrauchte IT, (3) Digitale Bildung — Knowhow-Portal und IT-Hilfe. Die Plattform ist bereits gebaut und kann als Prototype-Fund-Einreichung eingereicht werden. Runde 5 voraussichtlich bald offen. Alle Ergebnisse stehen bereits unter Open-Source-Lizenz. Kontakt: info@prototypefund.ch oder Newsletter abonnieren.',
    needsResearch: false,
    contact: {
      email: 'info@prototypefund.ch',
    },
  },
  {
    slug: 'migros-getconnected',
    name: 'Migros "Rein ins Netz!" / "Get connected!"',
    type: 'D',
    status: 'closed',
    deadline: null,
    deadlineText: 'Runde 2025 abgeschlossen (Fristen waren 15. August und 31. Oktober 2025). Keine Runde 2026 angekündigt.',
    amount: { min: 2000, max: 10000, text: "CHF 2'000 - 10'000" },
    fit: 3,
    priority: 2,
    tagline: 'Digitale Inklusion f\u00FCr finanziell Benachteiligte - PERFEKTER FIT!',
    region: 'Schweiz',
    applicationUrl: 'https://engagement.migros.ch/en/culture-percentage/social-affairs/getconnected',
    websiteUrl: 'https://engagement.migros.ch',
    applicationMethod: 'online',
    contact: {
      email: 'isabelle.ruckli@mgb.ch',
    },
    stats2025: "45 Projekte, CHF 362'205",
    purposeSummary: 'Migros-Kulturprozent-Programm zur Förderung von Projekten, die finanziell benachteiligten Menschen digitale Kompetenzen vermitteln. CHF 2\'000-10\'000 pro Projekt. 45 Organisationen in der 2025-Runde mit insgesamt CHF 362\'205 gefördert.',
    applicationProcess: [
      'Bewerbungsfenster abwarten (ca. Juni-Oktober)',
      'Online-Formular auf engagement.migros.ch ausf\u00FCllen',
      'Projektbeschreibung: Digitale Bildung f\u00FCr Benachteiligte',
      'Entscheid innerhalb von 2-3 Monaten',
    ],
    sourceLinks: [
      { source: 'website', url: 'https://engagement.migros.ch/en/culture-percentage/social-affairs/getconnected', label: 'Get connected! Programm' },
    ],
    themes: ['digitale-bildung', 'soziale-integration'],
    source: 'manual',
    researchDate: '2026-02-10',
    researchNotes: 'Runde 2025 ist abgeschlossen, keine Folgerunde 2026 angekündigt. Für künftige Runden Isabelle Ruckli kontaktieren: isabelle.ruckli@mgb.ch. Berechtigt: gemeinnützige Organisationen oder öffentliche Stellen in Partnerschaft mit Gemeinnützigen. Nicht berechtigt: Einzelpersonen, formale Bildung, Schullager, reine Infrastruktur.',
    needsResearch: false,
  },
  {
    slug: 'klimup',
    name: 'Stadt Z\u00FCrich KlimUp',
    type: 'D',
    status: 'closed',
    deadline: null,
    deadlineText: 'Aktuelle Runde geschlossen. Ursprüngliches Budget von CHF 14 Mio. weitgehend erschöpft. Stadtrat beantragte beim Gemeinderat zusätzliche CHF 3 Mio. Nächste Runde noch nicht angekündigt.',
    amount: { min: 5000, max: 600000, text: 'NPO: CHF 5k-100k (Projekt) / CHF 60k-600k (Betrieb, 2-4 J.)' },
    fit: 3,
    priority: 3,
    tagline: 'Das Z\u00FCrcher F\u00F6rderprogramm f\u00FCr Kreislaufwirtschaft',
    totalBudget: 'CHF 14 Mio. (+ CHF 3 Mio. f\u00FCr 2026 beantragt)',
    region: 'Stadt Z\u00FCrich',
    applicationUrl: 'https://www.stadt-zuerich.ch/de/umwelt-und-energie/klima/beratung-und-foerderung/klimup.html',
    websiteUrl: 'https://www.stadt-zuerich.ch/de/umwelt-und-energie/klima/beratung-und-foerderung/klimup.html',
    applicationMethod: 'online',
    sourceLinks: [
      { source: 'cantonal', url: 'https://www.stadt-zuerich.ch/de/umwelt-und-energie/klima/beratung-und-foerderung/klimup.html', label: 'Stadt Z\u00FCrich KlimUp' },
    ],
    themes: ['zuerich', 'kreislaufwirtschaft', 'klima'],
    source: 'manual',
    researchDate: '2026-02-10',
    purposeSummary: 'Programm der Stadt Zürich zur Förderung von Startups (CHF 35\'000-250\'000) und NPOs (Projekte CHF 5\'000-100\'000, Betrieb CHF 60\'000-600\'000 über 2-4 Jahre) in Klimaschutz und Kreislaufwirtschaft.',
    researchNotes: 'Startups müssen max. 5 Jahre alt sein, Gründer mind. 50% Anteile halten, Standort Zürich erforderlich. NPOs müssen steuerbefreit sein mit Schweizer Sitz oder Niederlassung. Zusatzkredit von CHF 3 Mio. soll weitere Förderrunde 2026 ermöglichen. Anfang 2026 externe Evaluation geplant. Kontakt: René Estermann, Direktor Umwelt- und Gesundheitsschutz.',
    needsResearch: false,
    contact: {
      email: 'rene.estermann@zuerich.ch',
      phone: '+41 44 412 47 54',
    },
  },

  // ---- PRIORITY 3: Research Needed - From ESA Registry ----
  {
    slug: 'stellennetz',
    name: 'Stiftung Stellennetz',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Keine festen Fristen. Stellennetz ist kein klassischer Fördergeldgeber, sondern ein potenzieller Partnerschafts-/Programmanbieter für Arbeitsintegration. Kontakt direkt aufnehmen.',
    amount: { min: null, max: null, text: 'Nicht anwendbar' },
    fit: 1,
    priority: 1,
    tagline: 'OPERATIV: Betreibt eigene Programme, vergibt keine F\u00F6rdergelder',
    uid: 'CHE-310.604.106',
    region: 'Z\u00FCrich',
    websiteUrl: 'https://stellennetz-zh.ch/',
    applicationMethod: 'none',
    purposeSummary: 'Stiftung für Arbeitsintegration in Zürich. Seit über 40 Jahren begleitet Stellennetz Stellensuchende mit Kursen, Coaching und Vermittlung zurück in den Arbeitsmarkt. Angebote für Sozialhilfeempfänger, Unternehmen und Geflüchtete.',
    sourceLinks: [
      { source: 'zefix', url: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE310604106&directLink=true', label: 'Zefix-Eintrag' },
      { source: 'esa', url: 'https://www.esa.admin.ch/de/stiftungsverzeichnis', label: 'ESA Stiftungsverzeichnis' },
    ],
    themes: ['zuerich', 'arbeitsintegration', 'soziale-integration'],
    source: 'esa',
    researchDate: '2026-02-09',
    needsResearch: false,
    isOperative: true,
    researchNotes: 'KEINE fördernde Stiftung im klassischen Sinn — Stellennetz ist selbst ein Anbieter von Arbeitsintegration. Für Revamp-IT relevant als potenzieller Kooperationspartner: Stellennetz vermittelt Stellensuchende in den primären Arbeitsmarkt und sucht aktiv Partnerbetriebe (\'Partner werden\'-Programm). Revamp-IT könnte als Einsatzbetrieb für Arbeitsintegrations-Teilnehmende fungieren. Angebote umfassen Deutschkurse, Job-Coaching, externe Arbeitseinsätze und das Jugendprojekt \'Xplore\'. Seit 2014 eigenständige Stiftung, QM-zertifiziert (KIP). Mitglied bei Arbeitsintegration Schweiz.',
    contact: {
      address: 'Räffelstrasse 20, 8045 Zürich',
      email: 'info@stellennetz-zh.ch',
      phone: '+41 44 297 91 91',
    },
  },
  {
    slug: 'climatoor',
    name: 'Stiftung climatoor',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Kontakt aufnehmen',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 2,
    priority: 2,
    tagline: 'Umwelt- & Klimaschutz, Bildung, Wissenschaft',
    uid: 'CHE-298.041.207',
    region: 'Z\u00FCrich',
    websiteUrl: 'https://app.spheriq.ch/organisation/stiftung-climatoor',
    applicationMethod: 'direct',
    purposeSummary: 'Gemeinnützige Stiftung zur Förderung von Umwelt- und Klimaschutz durch Unterstützung von Projekten, Wissenschaft/Forschung und Bildung/Aufklärung. Kann in der Schweiz und im Ausland inkl. Entwicklungsländern tätig sein.',
    sourceLinks: [
      { source: 'zefix', url: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE298041207&directLink=true', label: 'Zefix-Eintrag' },
      { source: 'stiftungschweiz', url: 'https://app.spheriq.ch/organisation/stiftung-climatoor', label: 'Spheriq-Profil' },
    ],
    themes: ['zuerich', 'klima', 'digitale-bildung'],
    source: 'esa',
    researchDate: '2026-02-10',
    needsResearch: false,
    researchNotes: 'Sehr neue Stiftung (registriert 02.03.2023). Stiftungsrat: André Frei (Präsident), Cornelia Frei-Handschin, Pascal Frei — Familienstiftung. Domizil bei ZKB (c/o Zürcher Kantonalbank, Stiftungen WFES, Bahnhofstrasse 9, 8001 Zürich). Keine Website, kein öffentliches Antragsverfahren. Keine Finanzdaten. Zweck passt teilweise zu Revamp-IT (Umweltschutz durch E-Waste-Reduktion/Kreislaufwirtschaft). Stiftung erscheint sehr neu, möglicherweise noch nicht aktiv bei Fördermittelvergabe. Mittlerer Fit — Monitoring empfohlen oder spekulative Anfrage an ZKB Stiftungen WFES.',
    contact: {
      address: 'c/o Balmer-Etienne AG, Bederstrasse 66, 8002 Zürich',
    },
  },
  {
    slug: 'z43-netzero',
    name: 'Z43 NetZero Stiftung',
    type: 'B',
    status: 'closed',
    deadline: null,
    deadlineText: 'Unternehmensstiftung des Z43-Campus (SPEAG/IT\'IS/ZMT). Keine externen Gesuche. Finanzierung durch E-Fuel-Kostenaufschlag der Campusfirmen.',
    amount: { min: 300000, max: 600000, text: 'USD 300-600k/Jahr (gesamt)' },
    fit: 2,
    priority: 2,
    tagline: 'Klimaneutrale Technologien & Forschung',
    uid: 'CHE-281.354.514',
    region: 'Z\u00FCrich / International',
    websiteUrl: 'https://www.fundraiso.ch/en/organisations/z43-netzero-stiftung',
    applicationMethod: 'direct',
    purposeSummary: 'Fördert Massnahmen und Projekte zur nachhaltigen Reduktion der Klimaauswirkungen menschlicher Aktivitäten mit dem Ziel der Klimaneutralität. Finanziert Klimaschutzprojekte, energieeffiziente Massnahmen, erneuerbare Energien und klimaneutrale Technologien.',
    sourceLinks: [
      { source: 'zefix', url: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE281354514&directLink=true', label: 'Zefix-Eintrag' },
      { source: 'fundraiso', url: 'https://www.fundraiso.ch/en/organisations/z43-netzero-stiftung', label: 'Fundraiso-Profil' },
    ],
    themes: ['zuerich', 'klima'],
    source: 'esa',
    researchDate: '2026-02-10',
    needsResearch: false,
    researchNotes: 'Junge Stiftung (gegründet 29.08.2024), entstanden aus dem Z43-Technologiezentrum (Zeughausstrasse 43, Zürich). Stiftungsrat: Prof. em. Niels Kuster, Dr. Roland Walthert, Dr. Davnah Urbach. Fördert insbesondere: Klimaschutzprojekte, energieeffiziente Massnahmen und erneuerbare Energien; Strukturen und Technologien für klimaneutrales Wirtschaften; wissenschaftliche Forschung zu nachhaltigen Klimaschutzmassnahmen. Wirkt in der Schweiz und im Ausland. Für Revamp-IT relevant: Refurbishing/Wiederverwendung von IT-Geräten als klimaneutrale Technologie positionieren (Vermeidung von Elektroschrott, Reduktion CO2-Ausstoss durch Lebensdauer-Verlängerung). UID: CHE-281.354.514.',
    contact: {
      address: 'Zeughausstrasse 43, 8004 Zürich',
      email: 'info@z43netzero.org',
    },
  },
  {
    slug: 'stopp-klimakrise',
    name: 'Stiftung Stopp Klimakrise - Kurt De Lorenzo',
    type: 'C',
    status: 'closed',
    deadline: null,
    deadlineText: 'Nimmt bis auf Weiteres keine Gesuche entgegen (bereits 2025 geschlossen)',
    amount: { min: null, max: null, text: 'Unbekannt (klein)' },
    fit: 2,
    priority: 2,
    tagline: 'Natur- und Klimaschutz, Ressourcenschonung - KLEINE STIFTUNG',
    uid: 'CHE-391.558.817',
    region: 'Z\u00FCrich',
    websiteUrl: 'https://stiftungen.stiftungschweiz.ch/organisation/stiftung-stopp-klimakrise-kurt-de-lorenzo',
    applicationMethod: 'personal',
    purposeSummary: 'Gemeinnützige Stiftung zur Förderung des Natur- und Klimaschutzes und der Erhaltung natürlicher Ressourcen im In- und Ausland, zur Bekämpfung des Klimawandels und Verbesserung der Umweltqualität für zukünftige Generationen.',
    sourceLinks: [
      { source: 'zefix', url: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE391558817&directLink=true', label: 'Zefix-Eintrag' },
    ],
    themes: ['zuerich', 'klima', 'kreislaufwirtschaft'],
    source: 'esa',
    researchDate: '2026-02-09',
    needsResearch: false,
    researchNotes: 'Kleine Familienstiftung (Kurt De Lorenzo). Stiftungsrat: Edwin Moser (Präsident), Christina Marchand, Kurt De Lorenzo. Gegründet 15. Mai 2022. Gleiche Adresse wie myclimate (Pfingstweidstrasse 10, 8005 Zürich). Stiftung nimmt explizit KEINE Gesuche entgegen seit 2025 und \'bis auf Weiteres.\' Zweck würde gut zu Revamp-IT passen (Ressourcenschonung, Klimaschutz), aber derzeit nicht zugänglich. Niedrige Priorität wegen geschlossenem Status. Periodisch prüfen.',
    contact: {
      address: 'Pfingstweidstrasse 10, 8005 Zürich',
    },
  },
  {
    slug: 'familie-schwarz',
    name: 'Familie Schwarz Stiftung',
    type: 'B',
    status: 'closed',
    deadline: null,
    deadlineText: 'WICHTIG: Stiftung nimmt KEINE unaufgeforderten Gesuche an. Verfügbare Mittel sind bereits gebunden. Bewerbungen werden nicht bearbeitet.',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 3,
    priority: 3,
    tagline: 'Umweltschutz, soziale Not, Jugend - GUTER FIT!',
    uid: 'CHE-466.408.960',
    region: 'Z\u00FCrich / Weltweit',
    websiteUrl: 'https://www.fundraiso.ch/sponsor/familie-schwarz-stiftung',
    applicationMethod: 'direct',
    purposeSummary: 'Kleine Familienstiftung in Zürich (gegründet 2022). Fördert materielle Hilfe für sozial und körperlich bedürftige Menschen (Pflege, Gesundheit, Wohnen), Musikförderung, Humanmedizin sowie Umweltschutzprojekte und landwirtschaftliche/handwerkliche Ausbildung in Entwicklungsländern.',
    sourceLinks: [
      { source: 'zefix', url: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE466408960&directLink=true', label: 'Zefix-Eintrag' },
      { source: 'fundraiso', url: 'https://www.fundraiso.ch/sponsor/familie-schwarz-stiftung', label: 'Fundraiso-Profil' },
    ],
    themes: ['zuerich', 'kreislaufwirtschaft', 'klima', 'jugend', 'soziale-integration'],
    source: 'esa',
    researchDate: '2026-02-09',
    needsResearch: false,
    researchNotes: 'Stiftung hat explizit kommuniziert, dass sie KEINE unaufgeforderten Anfragen wünscht und diese nicht bearbeitet. Mittel sind bereits gebunden. Für Revamp-IT daher NICHT geeignet für Direktbewerbung. Stiftungsratspräsident: Konrad Schwarz, Zürich. Förderbereiche theoretisch passend (Recycling, handwerkliche Ausbildung, Umweltschutz), aber praktisch nicht zugänglich. Politisch und konfessionell neutral.',
    contact: {
      address: 'Feldblumenstrasse 19a, 8048 Zürich',
    },
  },
  {
    slug: 'baitella-eberle',
    name: 'Baitella-Eberle Stiftung',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Keine publizierten Fristen. Neue Stiftung (gegründet 2024), Antragsverfahren noch nicht öffentlich dokumentiert. Kontakt über Zürcher Kantonalbank-Adresse.',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 3,
    priority: 3,
    tagline: 'Zukunftstechnologien, Innovation, Umwelt, benachteiligte Jugend - SUPER FIT!',
    uid: 'CHE-389.062.085',
    region: 'Z\u00FCrich / CH / Entwicklungsl\u00E4nder',
    websiteUrl: 'https://www.fundraiso.ch/de/organisations/baitella-eberle-stiftung',
    applicationMethod: 'direct',
    purposeSummary: 'Fördert gemeinnützige Institutionen in Bildung und Ausbildung von Kindern und Erwachsenen, mit Schwerpunkt auf Karriereförderung in zukunftsorientierten Technologien. Unterstützt innovative Ideen für Allgemeinheit und Umwelt sowie Natur- und Umweltschutzprojekte.',
    sourceLinks: [
      { source: 'zefix', url: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE389062085&directLink=true', label: 'Zefix-Eintrag' },
      { source: 'fundraiso', url: 'https://www.fundraiso.ch/de/organisations/baitella-eberle-stiftung', label: 'Fundraiso-Profil' },
    ],
    themes: ['zuerich', 'digitale-bildung', 'klima', 'jugend', 'soziale-integration'],
    source: 'esa',
    researchDate: '2026-02-10',
    needsResearch: false,
    researchNotes: 'Junge Stiftung (gegründet 2024), Hauptsitz bei ZKB. Stiftungsrat: Gabriela Baitella-Eberle und Reto Baitella (Ko-Präsidium), Roman Schiochet (Mitglied). Primärer Fokus: Bildung/Ausbildung mit Schwerpunkt zukunftsorientierte Technologien; innovative Ideen für Allgemeinheit und Umwelt; medizinische Behandlungen für bedürftige Kinder/Jugendliche. Sekundärer Fokus: Natur- und Umweltschutz, insbesondere Waldschutz in Berggebieten; humanitäre Hilfe. Primärer Wirkungsbereich Schweiz, aber auch Entwicklungsländer möglich. Für Revamp-IT relevant: Ausbildungsprogramme in zukunftsorientierten Technologien (Linux, IT-Refurbishing) und Umweltschutzaspekt (Kreislaufwirtschaft). UID: CHE-389.062.085.',
    contact: {
      address: 'Bahnhofstrasse 9, c/o Zürcher Kantonalbank, 8001 Zürich',
    },
  },
  {
    slug: 'foundation-regina',
    name: 'Foundation Regina',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Keine publizierten Fristen. Neue Stiftung (gegründet März 2024). Kontakt über STAIGER Rechtsanwälte AG.',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 2,
    priority: 2,
    tagline: 'Informatik & Umweltschutz - AKADEMISCHER FOKUS',
    uid: 'CHE-449.768.771',
    region: 'Z\u00FCrich / International',
    websiteUrl: 'https://www.fundraiso.com/en/organisations/foundation-regina',
    applicationMethod: 'via_partner',
    purposeSummary: 'Fördert und unterstützt Personen, die in der Schweiz in den Bereichen Energie, neue Technologien, IT, Infrastruktur und Umweltschutz forschen oder arbeiten. Vergibt auch Beiträge an Schweizer Hochschulen und fördert wissenschaftliche Zusammenarbeit.',
    sourceLinks: [
      { source: 'zefix', url: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE449768771&directLink=true', label: 'Zefix-Eintrag' },
    ],
    themes: ['zuerich', 'digitale-bildung', 'digitale-souveraenitaet', 'klima'],
    source: 'esa',
    researchDate: '2026-02-10',
    needsResearch: false,
    researchNotes: 'Junge Stiftung (gegründet 19.03.2024). Stiftungsrat: Dr. Marc Bernheim (Präsident), Dr. Rolf Halonbrenner, Michael Pesaro. Revisionsstelle: BDO AG. Förderbereiche: Energie, neue Technologien, IT, Infrastruktur, Umweltschutz (In- und Ausland); Beiträge an Schweizer Hochschulen/Fachhochschulen; Symposien, Konferenzen, Professuren; soziale und kulturelle Projekte; Hilfe für Bedürftige. Förderarten: Projektförderung und Individualförderung. Für Revamp-IT HOCHRELEVANT: IT und neue Technologien als expliziter Förderschwerpunkt. Open-Source/Linux als zukunftsweisende Technologie, IT-Refurbishing als Umweltschutz-Infrastruktur. UID: CHE-449.768.771.',
    contact: {
      address: 'c/o STAIGER Rechtsanwälte AG, Talacker 41, 8001 Zürich',
    },
  },
  {
    slug: 'futuri',
    name: 'Stiftung Futuri',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Direkte Anfrage',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 3,
    priority: 2,
    tagline: 'Ausbildung, berufliche & soziale Integration, Nachhaltigkeit - KONTAKT AUFNEHMEN',
    uid: 'CHE-325.640.105',
    region: 'Z\u00FCrich',
    websiteUrl: 'https://www.futuri.ch/',
    applicationMethod: 'direct',
    purposeSummary: 'Stiftung für berufliche Integration von Geflüchteten, bietet Supported Education, Supported Employment und Supported Transition Programme. Akkreditierte Programme finanziert über Integrationsbeiträge (FUTURI Work Integration Coaching und FUTURI Job Entry).',
    sourceLinks: [
      { source: 'zefix', url: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE325640105&directLink=true', label: 'Zefix-Eintrag' },
      { source: 'website', url: 'https://www.futuri.ch/', label: 'Stiftungs-Website' },
    ],
    themes: ['zuerich', 'arbeitsintegration', 'soziale-integration', 'jugend', 'klima'],
    source: 'esa',
    researchDate: '2026-02-10',
    needsResearch: false,
    researchNotes: 'Stiftung Futuri ist primär ein LEISTUNGSERBRINGER für Flüchtlingsintegration, keine fördernde Stiftung. Partnerschaftsmodell statt Förderanträge. Unterstützt Personen mit Flucht-/Gewalterfahrung oder schwierigen Lebensumständen. Kontakt: Marianne Bohn, Tel 044 552 72 42, marianne.bohn@futuri.ch.',
    contact: {
      address: 'Weinbergstrasse 29, 8006 Zürich',
      email: 'welcome@futuri.ch',
      phone: '+41 44 552 72 42',
    },
  },
  {
    slug: 'erde-2-0',
    name: 'ERDE 2.0 Stiftung',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Keine publizierten Fristen. Stiftung unterstützt primär akademische Forschungsprojekte in Zusammenarbeit mit Schweizer Institutionen.',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 2,
    priority: 2,
    tagline: 'Klimaresilienz & Technologie - AKADEMISCHER FOKUS',
    uid: 'CHE-443.701.461',
    region: 'Z\u00FCrich / CH / International',
    websiteUrl: 'https://stiftungen.stiftungschweiz.ch/organisation/erde-2-0-stiftung',
    applicationMethod: 'via_partner',
    purposeSummary: 'Gemeinnützige Stiftung zur Förderung der globalen menschlichen Gesundheit und Resilienz. Unterstützt wissenschaftliche Ideen, Methoden und Technologien, die der Menschheit helfen, sich an eine sich verändernde Welt anzupassen.',
    sourceLinks: [
      { source: 'zefix', url: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE443701461&directLink=true', label: 'Zefix-Eintrag' },
      { source: 'stiftungschweiz', url: 'https://stiftungen.stiftungschweiz.ch/organisation/erde-2-0-stiftung', label: 'StiftungSchweiz-Profil' },
    ],
    themes: ['zuerich', 'klima', 'digitale-bildung'],
    source: 'esa',
    researchDate: '2026-02-09',
    needsResearch: false,
    researchNotes: 'Gegründet 2023, Sitz in Zürich (c/o Centralis Switzerland GmbH). Förderbereiche: Klima-/Wetter-/Planetenwissenschaften, Ernährungs-/Energie-/Wassersicherheit (FEW), menschliche Gesundheit, resiliente natürliche Ökosysteme, Transport, technologische Innovation. Unterstützt primär akademische und innovative Initiativen von Schweizer Institutionen, kann aber auch an europäischen/globalen Initiativen teilnehmen. Gemeinnützig, kein kommerzieller Zweck. Für Revamp-IT: Eher geringe Passung, da Fokus auf akademischer Forschung liegt. Möglicher Ansatz: Forschungsprojekt zu digitaler Inklusion und Kreislaufwirtschaft in Kooperation mit einer Hochschule. UID: CHE-443.701.461.',
    contact: {
      address: 'Kanzleistrasse 18, c/o Centralis Switzerland GmbH, 8004 Zürich',
    },
  },
  {
    slug: 'responsability',
    name: 'responsAbility Foundation',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Keine publizierten Fristen. Neue Stiftung (gegründet 2024), Fokus auf katalytisches Kapital für Impact-Investments in Entwicklungs- und Schwellenländern.',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 1,
    priority: 1,
    tagline: 'UN SDGs, Entwicklungsl\u00E4nder - NICHT F\u00DCR CH-PROJEKTE',
    uid: 'CHE-389.004.225',
    region: 'Entwicklungsl\u00E4nder',
    websiteUrl: 'https://zh.chregister.ch/cr-portal/auszug/auszug.xhtml?uid=CHE-389.004.225',
    applicationMethod: 'unknown',
    purposeSummary: 'Gemeinnützige Stiftung, die mit unternehmerischen Mitteln zu den UN-Nachhaltigkeitszielen beiträgt, insbesondere Armutsbekämpfung. Stellt katalytisches Kapital bereit (Schulden, Eigenkapital, Garantien) für wirkungsorientierte Investitionen.',
    sourceLinks: [
      { source: 'zefix', url: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE389004225&directLink=true', label: 'Zefix-Eintrag' },
      { source: 'cantonal', url: 'https://zh.chregister.ch/cr-portal/auszug/auszug.xhtml?uid=CHE-389.004.225', label: 'Handelsregister Z\u00FCrich' },
    ],
    themes: ['klima', 'soziale-integration'],
    source: 'esa',
    researchDate: '2026-02-09',
    needsResearch: false,
    researchNotes: 'Gegründet 2024, verbunden mit responsAbility Investments AG (führender Impact-Investor mit Sitz in Zürich). Stiftungsrat: Tara Hesse (Präsidentin, Davos), Simon Fritschi (Mitglied, Zürich). Fokus auf SDGs, insbesondere: Armutsbekämpfung, Zero Hunger, saubere Energie, Klimaschutz, wirtschaftliche Chancen in Entwicklungsländern. Katalytisches Kapital akzeptiert höheres Risiko/tiefere Rendite für positive Wirkung. Unter Aufsicht der Eidg. Stiftungsaufsicht (BJ). Für Revamp-IT: GERINGE Passung — Fokus liegt auf Entwicklungs-/Schwellenländer-Investments, nicht auf Schweizer Sozialunternehmen. Nur relevant, falls Revamp-IT internationale Expansion plant.',
    contact: {
      address: 'Zollstrasse 17, 8005 Zürich',
    },
  },
  {
    slug: 'landscape-resilience',
    name: 'Landscape Resilience Fund',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Keine festen Fristen. Fokus auf Entwicklungs- und Schwellenländer. Kontakt über Website landscaperesiliencefund.org.',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 1,
    priority: 1,
    tagline: 'Klimaanpassung, Entwicklungsl\u00E4nder - NICHT F\u00DCR CH-PROJEKTE',
    uid: 'CHE-485.173.674',
    region: 'Entwicklungsl\u00E4nder',
    websiteUrl: 'https://landscaperesiliencefund.org/',
    applicationMethod: 'unknown',
    purposeSummary: 'Unabhängige Schweizer Stiftung, die private und öffentliche Klimafinanzierung für gefährdete Kleinbauern und Landschaften mobilisiert. Gegründet von WWF und South Pole, verwaltet von South Pole.',
    sourceLinks: [
      { source: 'zefix', url: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE485173674&directLink=true', label: 'Zefix-Eintrag' },
    ],
    themes: ['klima'],
    source: 'esa',
    researchDate: '2026-02-09',
    needsResearch: false,
    researchNotes: 'Gegründet 2021 (WWF + South Pole). Drei Fördersäulen: integrierter Landschaftsansatz; technische Unterstützung für KMU in Richtung Investitionsreife; konzessionäre Darlehen an KMU. Ankerinvestor: Chanel (USD 25 Mio.), zusätzlich GEF-Mittel. Ziel: USD 100 Mio. bis 2025. Tätig in Brasilien (Amazonas), Vietnam, Indonesien, Malaysia, Indien. Für Revamp-IT: KEINE Passung — Fokus liegt ausschliesslich auf Entwicklungsländern, nachhaltige Landwirtschaft/Forstwirtschaft und Klimaanpassung für Kleinbauern. Nicht relevant für Schweizer IT-Refurbishing.',
    contact: {
      address: 'c/o Büttler | Benn Rechtsanwälte, Vorderberg 11, 8044 Zürich',
    },
  },
  {
    slug: 'rethink',
    name: 'Stiftung Rethink!',
    type: 'C',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Kein Antragsverfahren gefunden — Stiftung befindet sich noch im Aufbau, sucht selbst Finanzierung',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 3,
    priority: 2,
    tagline: 'Repair Centers, Secondhand Centers - POTENTIELLER PARTNER!',
    uid: 'CHE-190.533.848',
    region: 'Aarau / CH',
    websiteUrl: 'https://www.fundraiso.com/en/organisations/stiftung-rethink',
    applicationMethod: 'partnership',
    purposeSummary: 'Stiftung zur Umsetzung von 26 Missionen aus der Publikation \'RETHINK THE WORLD\', u.a. Ende der Wegwerfgesellschaft durch Repair Centers, Secondhand Centers und Rental Centers; Förderung von Hilfe zur Selbsthilfe; globale Bildungszugänglichkeit.',
    sourceLinks: [
      { source: 'zefix', url: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE190533848&directLink=true', label: 'Zefix-Eintrag' },
      { source: 'fundraiso', url: 'https://www.fundraiso.com/en/organisations/stiftung-rethink', label: 'Fundraiso-Profil' },
    ],
    themes: ['kreislaufwirtschaft', 'klima'],
    source: 'esa',
    researchDate: '2026-02-10',
    needsResearch: false,
    researchNotes: 'Sehr neue Stiftung (8. Feb. 2023). Stiftungsrat: Tizian Sebastian Cléo Baldinger (Präsident), Xiayo Wang (Berlin), Ivan Hörler (seit Aug. 2025). Website: rethink.to/de. Mission \'Ende der Wegwerfgesellschaft durch Repair/Secondhand Centers\' passt SEHR GUT zu Revamp-IT. Aber: Stiftung sucht selbst noch Finanzierung und Personal. Eher PARTNER als GELDGEBER in dieser Phase. HOHER konzeptioneller Fit, NIEDRIG als Finanzierungsquelle. Kontakt für Partnerschaft/Zusammenarbeit empfohlen.',
    contact: {
      address: 'Aarestrasse 38, 5000 Aarau',
    },
  },
  {
    slug: 'globility-circle',
    name: 'Stiftung Globility Circle',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Keine festen Fristen — laufende Anfragen auf Rolling-Basis',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 2,
    priority: 2,
    tagline: 'Soziales Unternehmertum, \u00F6kologischer Fortschritt',
    uid: 'CHE-114.571.634',
    region: 'Luzern / CH',
    websiteUrl: 'https://globility-circle.org/',
    applicationMethod: 'direct',
    purposeSummary: 'Fördert Social Entrepreneurship durch nicht-materielle, fachliche und finanzielle Unterstützung von Projekten und Personen, die sich für sozialen, ökologischen und kulturellen Fortschritt engagieren. Schwerpunkt: Beratung/Vernetzung sozial engagierter Unternehmer und nachhaltiger Konsum.',
    sourceLinks: [
      { source: 'zefix', url: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE114571634&directLink=true', label: 'Zefix-Eintrag' },
      { source: 'website', url: 'https://globility-circle.org/', label: 'Stiftungs-Website' },
    ],
    themes: ['soziale-integration', 'klima'],
    source: 'esa',
    researchDate: '2026-02-09',
    needsResearch: false,
    researchNotes: 'Etablierte Stiftung (gegr. 3. Nov. 2008). Stiftungsrat: Köller-Familie: Heinz Köller (Präsident), Fabian, Marcel, Manuel Köller. Statuten geändert 19.11.2025 (kürzlich aktiv). Vier Themenbereiche: Umwelt, Finanzen, Gesundheit, Soziales Verhalten. Motto: \'Global denken — regional handeln.\' Revamp-IT passt GUT: Social Entrepreneurship (Arbeitsintegration), ökologischer Fortschritt (E-Waste-Reduktion), nachhaltiger Konsum (aufbereitete Computer statt neue). Persönlicher Kontakt mit Heinz Köller empfohlen.',
    contact: {
      address: 'c/o Bolzern Haas & Partner AG, Winkelriedstrasse 35, 6003 Luzern',
      email: 'hkoeller@bluewin.ch',
      phone: '+41 41 669 11 11',
    },
  },
  {
    slug: 'fair-recycling',
    name: 'Stiftung Fair Recycling',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Keine Fördergesuche möglich. Fair Recycling ist operativ tätig (Kühlschrank-Recycling in Brasilien), kein Fördergeldgeber.',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 1,
    priority: 1,
    tagline: 'E-Waste Recycling - INTERNATIONALE PROJEKTE',
    uid: 'CHE-114.639.568',
    region: 'International (nicht CH)',
    websiteUrl: 'https://stiftungen.stiftungschweiz.ch/organisation/stiftung-fair-recycling',
    applicationMethod: 'unknown',
    purposeSummary: 'Klimaschutzstiftung mit Sitz in Aarau. Seit 2008 recycelt Fair Recycling Kühlschränke nach Schweizer Standards in Brasilien (Partner: Indústria Fox). FCKW-Gase sind 10\'000 Mal klimaschädlicher als CO2.',
    sourceLinks: [
      { source: 'zefix', url: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE114639568&directLink=true', label: 'Zefix-Eintrag' },
      { source: 'stiftungschweiz', url: 'https://stiftungen.stiftungschweiz.ch/organisation/stiftung-fair-recycling', label: 'StiftungSchweiz-Profil' },
    ],
    themes: ['kreislaufwirtschaft', 'klima'],
    source: 'esa',
    researchDate: '2026-02-09',
    needsResearch: false,
    researchNotes: 'KEIN Fördergeldgeber — Fair Recycling ist selbst eine operative Klimaschutzorganisation. Wirkung: 1.5 Mio. Kühlschränke recycelt, 1.8 Mio. Tonnen CO2-Äquivalente jährlich eingespart, 95% Materialrückgewinnung, 300 Arbeitsplätze mit fairen Bedingungen, 11\'000 Stunden Mitarbeiterschulung. SWISS CHARTER als Standard (mit Unterstützung BAFU, SECO, DEZA). 40+ Klimapartner in der Schweiz. Für Revamp-IT: Potenzielle Partnerschaft/Netzwerkverbindung als verwandtes Sozialunternehmen im Recycling-Bereich. Kein Förderkanal, aber Erfahrungsaustausch zu CO2-Zertifikaten und Kreislaufwirtschaft möglich.',
    contact: {
      address: 'Kirschgartenweg 13, c/o Dr. Andreas Röthlisberger, 5000 Aarau',
    },
  },
  {
    slug: 'wirtschaft-gesellschaft',
    name: 'Stiftung f\u00FCr Wirtschaft und Gesellschaft',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Keine festen Fristen — Anträge werden laufend geprüft',
    amount: { min: null, max: null, text: 'Darlehen/Beteiligung' },
    fit: 3,
    priority: 3,
    tagline: 'Nachhaltiges Unternehmertum, KMU, Arbeitspl\u00E4tze - SEHR RELEVANT!',
    uid: 'CHE-344.116.046',
    region: 'Heimberg / CH',
    websiteUrl: 'https://app.spheriq.ch/organisation/stiftung-fuer-wirtschaft-und-gesellschaft',
    applicationMethod: 'direct',
    purposeSummary: 'Fördert verantwortungsvolles und nachhaltiges Unternehmertum in KMU, mit Fokus auf Arbeitsplatzschaffung (auch für Menschen mit eingeschränkter Arbeitsfähigkeit), soziale Herausforderungen, Gesundheit und Freiwilligenarbeit.',
    sourceLinks: [
      { source: 'zefix', url: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE344116046&directLink=true', label: 'Zefix-Eintrag' },
      { source: 'stiftungschweiz', url: 'https://app.spheriq.ch/organisation/stiftung-fuer-wirtschaft-und-gesellschaft', label: 'Spheriq-Profil' },
    ],
    themes: ['soziale-integration', 'arbeitsintegration'],
    source: 'esa',
    researchDate: '2026-02-09',
    needsResearch: false,
    researchNotes: 'Gegründet 24. Aug. 2014, Aufsicht durch EDI. Stiftungsrat: David Hug (Präsident), Werner Jakob, Marc Schachtler, Stefan Jakob. Eng verbunden mit Vita Perspektiv AG (gleiche Adresse, Website: vitaperspektiv.ch). Beträchtliches Vermögen (10-50 Mio. CHF). Bietet Projekt- UND Einzelförderung. Instrumente: Darlehen, Kapitalbeteiligungen, Coaching, Ausbildung, Vernetzung. Erwähnt explizit \'Schaffung und Erhaltung von Arbeitsplätzen, soweit möglich auch für Personen mit eingeschränkter Arbeitsfähigkeit\' und \'Arbeitsintegration\' — AUSGEZEICHNETER Fit für Revamp-IT. SEHR HOHER FIT besonders für Arbeitsintegration.',
    contact: {
      address: 'c/o Vita Perspektiv AG, Winterhaldenstrasse 12, 3627 Heimberg',
      email: 'info@vitaperspektiv.ch',
      phone: '033 439 30 90',
    },
  },
  {
    slug: 'svc-unternehmertum',
    name: 'SVC Stiftung f\u00FCr das Unternehmertum',
    type: 'A',
    status: 'open',
    deadline: null,
    deadlineText: 'ENTERPRIZE 2026: Bewerbungsfrist bis 15. April 2026. Preis für innovative Berufsbildungsprojekte. Projekteinreichung über svc-stiftung.swiss möglich.',
    amount: { min: null, max: null, text: 'Projektf\u00F6rderung' },
    fit: 2,
    priority: 2,
    tagline: 'KMU-F\u00F6rderung, Unternehmertum, Bildung',
    uid: 'CHE-217.027.356',
    region: 'G\u00FCmligen / CH',
    websiteUrl: 'https://svc-stiftung.swiss/',
    applicationMethod: 'direct',
    purposeSummary: 'Fördert unternehmerisches Denken und Handeln in der Schweiz, insbesondere KMU. Sensibilisiert für Unternehmertum und unterstützt zukunftsträchtige Projekte. Vergibt den ENTERPRIZE für innovative Berufsbildungsprojekte.',
    sourceLinks: [
      { source: 'zefix', url: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE217027356&directLink=true', label: 'Zefix-Eintrag' },
      { source: 'website', url: 'https://svc-stiftung.swiss/', label: 'SVC Stiftung Website' },
    ],
    themes: ['digitale-bildung'],
    source: 'esa',
    researchDate: '2026-02-09',
    needsResearch: false,
    researchNotes: 'SVC Stiftung arbeitet in Personalunion mit Swiss Venture Club, ist aber rechtlich eigenständig. Unter Eidg. Stiftungsaufsicht. Zwei Schwerpunkte: 1) Innovation & Exzellenz (Unternehmerpreise, Best Practices); 2) Unternehmertum-Bildung (Gründerkompetenz, Startup-Förderung). ENTERPRIZE 2026 (10. Ausgabe): Sucht innovative Berufsbildungsprojekte, Patronat von Bundesrat Guy Parmelin und Schweizerischem Arbeitgeberverband, Bewerbung bis 15.04.2026. Weitere Projekte: \'Talent Pitch\', \'Youngpreneurs\' (Jugend-Startup-Förderung). Für Revamp-IT: RELEVANT — Arbeitsintegrationsprogramm als innovatives Berufsbildungsprojekt für ENTERPRIZE positionieren. Auch Projekteinreichung über Website möglich. Kontakt: Michael Fahrni (michael.fahrni@svc.swiss).',
    contact: {
      address: 'c/o SVC Swiss Venture Club, Bernapark 28, 3066 Stettlen',
      email: 'svc.stiftung@svc.swiss',
      phone: '+41 31 819 69 00',
    },
  },

  // ---- Networks & Resources (not direct funders) ----
  {
    slug: 'netzwerk-sds',
    name: 'Netzwerk SDS',
    type: 'network',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Netzwerk offen für neue Mitgliedsorganisationen. Kein Förderinstrument, sondern Vernetzungsplattform. Innosuisse-Antrag eingereicht (Stand Oktober 2025).',
    amount: { min: null, max: null, text: 'Netzwerk (keine direkte F\u00F6rderung)' },
    fit: 2,
    priority: 4,
    tagline: 'Souver\u00E4ne Digitale Schweiz',
    members: '100+ Organisationen',
    region: 'Schweiz',
    applicationUrl: 'https://netzwerksds.ch/',
    websiteUrl: 'https://netzwerksds.ch',
    applicationMethod: 'membership',
    partners: ['BFH', 'EJPD', 'Stadt Z\u00FCrich', 'Post', 'SWITCH'],
    isNetwork: true,
    sourceLinks: [
      { source: 'website', url: 'https://netzwerksds.ch/', label: 'Netzwerk SDS Website' },
    ],
    themes: ['digitale-souveraenitaet'],
    source: 'manual',
    researchDate: '2026-02-10',
    purposeSummary: 'Netzwerk Souveräne Digitale Schweiz fördert digitale Souveränität in der Schweiz durch Vernetzung, Wissens- und Erfahrungstransfer. Über 100 Organisationen beteiligt. Gegründet am 28. August 2025.',
    researchNotes: 'KEIN Fördergeldgeber — Netzwerk SDS ist eine Vernetzungsplattform für digitale Souveränität. Gegründet durch BFH (Institut IPST), EJPD, OIZ Stadt Zürich und Schweizerische Post. Themen: Reduktion von Herstellerabhängigkeiten, Open-Source-Technologien, souveräner Betrieb von IT-Infrastrukturen. Kooperation mit deutschem ZenDiS geplant (openDesk-Angebot für Schweiz). Beirat: Dominika Blonski (Datenschutz ZH), Danielle Kaufmann (Datenschutz BS), Werner Kipfer (OIZ Zürich), Matthias Schmutz (EJPD). Innosuisse-Antrag wurde eingereicht. USA lobbyieren aktiv dagegen (Republik-Bericht Jan 2026). Für Revamp-IT HOCHRELEVANT: Mitgliedschaft als Open-Source-/Linux-Anbieter. Revamp-IT installiert Linux auf wiederaufbereiteten Geräten — direkt relevant für digitale Souveränität. Vernetzung mit Behörden und IT-Firmen.',
    needsResearch: false,
    contact: {
      address: 'c/o BFH, Institut IPST, Bern',
      email: 'info@netzwerksds.ch',
    },
  },
  {
    slug: 'ch-open',
    name: 'CH Open',
    type: 'network',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Mitgliedschaft jederzeit möglich. Nächste Events: Business Apéro 19.02.2026, Nextcloud-Talk 25.02.2026, GV 23.03.2026. Open Education Day 2026 im Mai.',
    amount: { min: null, max: null, text: 'CHF ~200/Jahr (Verein)' },
    fit: 2,
    priority: 4,
    tagline: 'Open Source Community seit 1982',
    members: '~200 Personen, 54 Kollektiv, 53 Sponsoren',
    region: 'Schweiz',
    applicationUrl: 'https://www.ch-open.ch/en/',
    websiteUrl: 'https://www.ch-open.ch',
    applicationMethod: 'membership',
    events: ['DINAcon', 'Lunch Lectures'],
    isNetwork: true,
    sourceLinks: [
      { source: 'website', url: 'https://www.ch-open.ch/en/', label: 'CH Open Website' },
    ],
    themes: ['digitale-souveraenitaet'],
    source: 'manual',
    researchDate: '2026-02-09',
    purposeSummary: 'Verein zur Förderung von Open Source Software und Open Standards in der Schweizer ICT-Landschaft seit 1982. Über 330 Mitglieder (Premium, Kollektiv, Einzel, Bildung). Organisiert Events, Workshops und pflegt das OSS Directory.',
    researchNotes: 'KEIN Fördergeldgeber — CH Open ist ein Branchenverein für Open-Source-Förderung. Sitz bei BFH in Bern. Aktivitäten: OSS Directory (Plattform für Open-Source-News, Events, Firmen, Produkte, Jobs); DINAcon (Konferenz für digitale Nachhaltigkeit mit Awards); Open Education Day (Ressourcen für Schulen); Workshop Days (IT-Trainingsworkshops); BigBlueButton-Server; Open Education Server (Nextcloud). Mitgliederstruktur: 53 Premium, 62 Kollektiv, 222 Einzel, 5 Ehren. Für Revamp-IT HOCHRELEVANT: Mitgliedschaft als Linux-/Open-Source-Anbieter. Sichtbarkeit im OSS Directory, Networking an Events, mögliche Nominierung für DINAcon Award (digitale Nachhaltigkeit). Nächste GV: 23.03.2026.',
    needsResearch: false,
    contact: {
      address: 'Brückenstrasse 73, 3005 Bern',
      email: 'info@ch-open.ch',
    },
  },
  {
    slug: 'innosuisse',
    name: 'Innosuisse',
    type: 'A',
    status: 'open',
    deadline: null,
    deadlineText: 'Laufende Einreichung für Innovationsprojekte und Swiss Accelerator. Eurostars Call 10: Jan-März 2026. THCS Call 2026 (\'Access to care\') offen.',
    amount: { min: null, max: null, text: 'Variabel (substanziell)' },
    fit: 1,
    priority: 4,
    tagline: 'F\u00F6rderagentur f\u00FCr Innovation',
    region: 'Schweiz',
    applicationUrl: 'https://www.innosuisse.admin.ch/en/support-offers',
    websiteUrl: 'https://www.innosuisse.admin.ch',
    applicationMethod: 'partnership',
    requiresPartner: true,
    possiblePartners: ['BFH', 'ZHAW', 'Empa'],
    sourceLinks: [
      { source: 'website', url: 'https://www.innosuisse.admin.ch/en/support-offers', label: 'Förderangebote' },
    ],
    themes: ['kreislaufwirtschaft', 'digitale-souveraenitaet'],
    source: 'manual',
    researchDate: '2026-02-10',
    purposeSummary: 'Schweizerische Agentur für Innovationsförderung. Unterstützt KMU, Start-ups und Forschungsinstitutionen bei Forschung und Entwicklung. Fördert bis 70% der Projektkosten bei Start-up-Innovationsprojekten.',
    researchNotes: 'Bundesagentur für Innovationsförderung. Hauptprogramme: 1) Innovationsprojekte (national, mit Forschungspartner); 2) Start-up-Innovationsprojekte (bis 70% Förderung, mind. 30% Eigenanteil); 3) Swiss Accelerator (nach Markteintritt, Kommerzialisierung); 4) Eurostars (international, Call 10: Jan-März 2026, Call 11: Juli-Sept 2026); 5) Innowwide (internationale Markterschliessung). Bewerbung über Innolink-Plattform. Innosuisse Guide hilft bei Programmwahl. Für Revamp-IT: RELEVANT, aber anspruchsvoll — benötigt Forschungspartner (z.B. ZHAW, BFH) für Innovationsprojekt. Mögliche Projektideen: Forschung zu sozial-ökologischem IT-Refurbishing, digitale Inklusion, Kreislaufwirtschafts-Methodik für IT-Geräte. Swiss Accelerator für Skalierung des Solidarpreismodells. Netzwerk SDS hat ebenfalls Innosuisse-Antrag gestellt.',
    needsResearch: false,
    contact: {
      address: 'Einsteinstrasse 2, 3003 Bern',
    },
  },
  {
    slug: 'swico',
    name: 'Swico Innovationsfonds',
    type: 'D',
    status: 'open',
    deadline: null,
    deadlineText: 'Zweimal jährlich: 15. Februar und 15. August. Nächste Frist: 15. Februar 2026 (imminent!). Kontakt: roger.gnos@swico.ch.',
    amount: { min: null, max: 300000, text: "bis CHF 300'000" },
    fit: 1,
    priority: 4,
    tagline: "Bis CHF 300k f\u00FCr IT-Recycling-Projekte",
    region: 'Schweiz',
    applicationUrl: 'https://www.swico.ch/de/recycling/innovationsfonds/',
    websiteUrl: 'https://www.swico.ch/de/recycling/innovationsfonds/wer-kann-sich-bewerben/',
    applicationMethod: 'contract',
    requiresContract: true,
    sourceLinks: [
      { source: 'website', url: 'https://www.swico.ch/de/recycling/innovationsfonds/wer-kann-sich-bewerben/', label: 'Bewerbungskriterien' },
    ],
    themes: ['kreislaufwirtschaft'],
    source: 'manual',
    researchDate: '2026-02-10',
    purposeSummary: 'Wirtschaftsverband für die digitale Schweiz mit über 700 Mitgliedern. Betreibt SWICO Recycling (600+ Sammelstellen, 40\'000 Tonnen Elektroschrott jährlich) und einen Umweltinnovationsfonds mit bis zu CHF 300\'000 pro Projekt.',
    researchNotes: 'SWICO ist primär ein Branchenverband (nicht Förderstiftung), aber betreibt den Umweltinnovationsfonds für zukunftsweisende Recyclingprojekte. Innovationsfonds: Finanziert durch SWICO Recycling, Entscheidung durch Experten-Komitee. Wer kann sich bewerben: Recyclingunternehmen, Hersteller und andere SWICO-Ökosystem-Teilnehmer (Vertragspartner); Kooperationen mit Start-ups oder Forschungsinstitutionen möglich. Projekte müssen innovativ, relevant, machbar sein. Kontakt: Roger Gnos (+41 44 446 90 96, roger.gnos@swico.ch). Ab 2026: Erhöhung der vorgezogenen Recyclinggebühr. 30-jähriges Jubiläum 2024, aktuell Pilotprojekte für Wiederverwendung (Reuse). Für Revamp-IT HOCHRELEVANT: Revamp-IT betreibt genau das, was SWICO mit \'Reuse-Pilotprojekten\' anstrebt. Innovationsfonds-Bewerbung für IT-Refurbishing-Methodik. Partnerschaft mit SWICO-Mitglied als Antragsteller möglich. Auch SWICO-Mitgliedschaft für Revamp-IT prüfen.',
    needsResearch: false,
    contact: {
      address: 'Lagerstrasse 33, 8004 Zürich',
      email: 'roger.gnos@swico.ch',
      phone: '+41 44 446 90 96',
    },
  },
];
