/**
 * Foundation Configuration Data
 *
 * Ported from assets/js/stiftungen-data.js to TypeScript.
 * Schema definitions live in lib/schemas/foundation.ts (SSOT).
 *
 * FOUNDATION TYPES (Robert Schmuki classification):
 * A = Professionalisierte Foerderstiftung
 * B = Potente Familienstiftung
 * C = Kleine Familienstiftung
 * D = Corporate Foundation
 * network = Netzwerk/Verband
 */

import type {
  Theme,
  ThemeId,
  Source,
  SourceId,
  Foundation,
  FoundationType,
  FoundationStatus,
  TypeLabel,
  StatusLabel,
} from '../schemas/foundation';

// ============================================================================
// THEME DEFINITIONS - Revamp-IT relevant categories
// ============================================================================

export const THEMES: Record<ThemeId, Theme> = {
  klima: {
    id: 'klima',
    label: 'Klima & Umwelt',
    icon: '\u{1F30D}',
    description: 'Klimaschutz, CO2-Reduktion, Nachhaltigkeit',
    color: '#10b981',
  },
  kreislaufwirtschaft: {
    id: 'kreislaufwirtschaft',
    label: 'Kreislaufwirtschaft',
    icon: '\u267B\uFE0F',
    description: 'Wiederverwendung, Reparatur, E-Waste',
    color: '#059669',
  },
  'soziale-integration': {
    id: 'soziale-integration',
    label: 'Soziale Integration',
    icon: '\u{1F91D}',
    description: 'Benachteiligte, Chancengleichheit, Second Chance',
    color: '#8b5cf6',
  },
  'digitale-bildung': {
    id: 'digitale-bildung',
    label: 'Digitale Bildung',
    icon: '\u{1F4BB}',
    description: 'IT-Workshops, Tech Skills, Medienkompetenz',
    color: '#3b82f6',
  },
  'digitale-souveraenitaet': {
    id: 'digitale-souveraenitaet',
    label: 'Digitale Souver\u00E4nit\u00E4t',
    icon: '\u{1F513}',
    description: 'Open Source, Linux, Unabh\u00E4ngigkeit',
    color: '#6366f1',
  },
  jugend: {
    id: 'jugend',
    label: 'Jugend',
    icon: '\u{1F465}',
    description: 'Jugendliche und junge Erwachsene (15-30)',
    color: '#f59e0b',
  },
  zuerich: {
    id: 'zuerich',
    label: 'Region Z\u00FCrich',
    icon: '\u{1F4CD}',
    description: 'Stadt oder Kanton Z\u00FCrich Fokus',
    color: '#ef4444',
  },
  arbeitsintegration: {
    id: 'arbeitsintegration',
    label: 'Arbeitsintegration',
    icon: '\u{1F4BC}',
    description: 'Arbeitsmarkt-Integration, Besch\u00E4ftigung',
    color: '#14b8a6',
  },
} as const satisfies Record<ThemeId, Theme>;

// ============================================================================
// SOURCE DEFINITIONS - Where we found the foundation
// ============================================================================

export const SOURCES: Record<SourceId, Source> = {
  manual: {
    id: 'manual',
    label: 'Eigenrecherche',
    description: 'Direkt recherchiert oder durch Netzwerk gefunden',
  },
  fundraiso: {
    id: 'fundraiso',
    label: 'Fundraiso.ch',
    url: 'https://www.fundraiso.ch',
    description: "13'300+ Schweizer Stiftungen",
  },
  stiftungschweiz: {
    id: 'stiftungschweiz',
    label: 'StiftungSchweiz',
    url: 'https://stiftungen.stiftungschweiz.ch',
    description: "~14'000 Stiftungen mit Filteroptionen",
  },
  esa: {
    id: 'esa',
    label: 'Eidg. Stiftungsaufsicht',
    url: 'https://www.esa.admin.ch/de/stiftungsverzeichnis',
    description: 'Offizielles Bundesregister',
  },
  robert: {
    id: 'robert',
    label: 'Robert Schmuki',
    description: 'Empfehlung aus Fundraising-Workshop',
  },
} as const satisfies Record<SourceId, Source>;

// ============================================================================
// FOUNDATION DATA - All 36 entries
// ============================================================================

export const STIFTUNGEN_DATA: Foundation[] = [
  // ---- PRIORITY 1: Apply Now (Deadline in 1-3 months) ----
  {
    slug: 'klimastiftung',
    name: 'Klimastiftung Schweiz',
    type: 'A',
    status: 'open',
    deadline: '2026-03-01',
    deadlineText: '1. M\u00E4rz 2026',
    nextDeadline: '1. September 2026',
    amount: { min: 5000, max: 200000, text: "bis CHF 200'000 (max. 50% Projektkosten)" },
    fit: 3,
    priority: 1,
    tagline: 'Die Stiftung, die KMUs beim Klimaschutz unterst\u00FCtzt',
    founded: 2008,
    annualBudget: 'ca. CHF 3 Mio.',
    region: 'CH/FL',
    applicationUrl: 'https://www.klimastiftung.ch/de/antrag-stellen/',
    websiteUrl: 'https://www.klimastiftung.ch',
    applicationMethod: 'online',
    themes: ['klima', 'kreislaufwirtschaft'],
    source: 'manual',
    researchDate: '2026-02-06',
  },
  {
    slug: 'ernst-goehner',
    name: 'Ernst G\u00F6hner Stiftung',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Min. 4 Monate vor Projektstart',
    amount: { min: 15000, max: 30000, text: "CHF 15'000 - 30'000 (typisch)" },
    fit: 3,
    priority: 1,
    tagline: 'Eine der gr\u00F6ssten Schweizer Stiftungen',
    founded: 1957,
    annualBudget: 'ca. CHF 40 Mio.',
    region: 'Schweiz',
    applicationUrl: 'https://ernst-goehner-stiftung.ch/index.php/de/services/Downloads',
    websiteUrl: 'https://ernst-goehner-stiftung.ch',
    applicationMethod: 'post',
    contact: {
      address: 'Ernst G\u00F6hner Stiftung, Artherstrasse 19, 6300 Zug',
      email: 'info@ernst-goehner-stiftung.ch',
      phone: '+41 41 729 66 33',
    },
    themes: ['soziale-integration', 'digitale-bildung', 'klima'],
    source: 'robert',
    researchDate: '2026-02-06',
  },
  {
    slug: 'binding',
    name: 'Sophie und Karl Binding Stiftung',
    type: 'A',
    status: 'open',
    deadline: '2026-03-31',
    deadlineText: '31. M\u00E4rz 2026',
    deadlines: [
      { date: '31. M\u00E4rz', response: 'Ende Juni' },
      { date: '30. Juni', response: 'Ende September' },
      { date: '22. September', response: 'Ende Dezember' },
      { date: '15. Dezember', response: 'Ende M\u00E4rz 2027' },
    ],
    amount: { min: 3000, max: 100000, text: "CHF 3'000 - 100'000+/Jahr" },
    fit: 3,
    priority: 1,
    tagline: 'Grosse Basler Stiftung mit Herz f\u00FCr Jugendintegration',
    region: 'Schweiz',
    applicationUrl: 'https://request-binding.alphafoundation.app',
    websiteUrl: 'https://www.binding-stiftung.ch',
    applicationMethod: 'online',
    contact: {
      email: 'contact@binding-stiftung.ch',
      phone: '+41 61 317 40 90',
    },
    themes: ['jugend', 'soziale-integration', 'arbeitsintegration', 'digitale-bildung'],
    source: 'robert',
    researchDate: '2026-02-06',
  },
  {
    slug: 'baugarten',
    name: 'Stiftung Baugarten Z\u00FCrich',
    type: 'B',
    status: 'open',
    deadline: '2026-05-01',
    deadlineText: '1. Mai 2026',
    amount: { min: 5000, max: 50000, text: "CHF 5'000 - 50'000" },
    fit: 3,
    priority: 1,
    tagline: 'Z\u00FCrcher Stiftung f\u00FCr soziale & \u00F6kologische Projekte',
    region: 'Stadt & Kanton Z\u00FCrich',
    applicationUrl: 'https://www.baugarten-zuerich.ch/gesuch',
    websiteUrl: 'https://www.baugarten-zuerich.ch',
    applicationMethod: 'online',
    themes: ['zuerich', 'soziale-integration', 'klima', 'digitale-bildung'],
    source: 'manual',
    researchDate: '2026-02-06',
  },

  // ---- PRIORITY 2: Rolling Applications ----
  {
    slug: 'mercator',
    name: 'Mercator Stiftung Schweiz',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Jederzeit',
    responseTime: '4 Wochen',
    amount: { min: 15000, max: 40000, text: "CHF 15'000 - 40'000+ (je nach Projekt)" },
    fit: 2,
    priority: 2,
    tagline: 'Digitalisierung + Gesellschaft als F\u00F6rderfeld',
    founded: 2006,
    region: 'Schweiz',
    applicationUrl: 'https://gesuch.stiftung-mercator.ch',
    websiteUrl: 'https://www.stiftung-mercator.ch',
    applicationMethod: 'online',
    themes: ['digitale-bildung', 'digitale-souveraenitaet'],
    source: 'robert',
    researchDate: '2026-02-06',
  },
  {
    slug: 'hirschmann',
    name: 'Hirschmann Stiftung',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: '6 Monate vor Projektbeginn',
    decisionCycle: '3x j\u00E4hrlich (Fr\u00FChling/Sommer/Winter)',
    amount: { min: null, max: null, text: 'Variabel (mehrj\u00E4hrig bevorzugt)' },
    fit: 3,
    priority: 2,
    tagline: 'Die Stiftung, die Grassroots-Projekte liebt',
    founded: 1985,
    region: 'Schweiz',
    applicationUrl: 'https://www.hirschmann-stiftung.ch/en/sponsorship/',
    websiteUrl: 'https://www.hirschmann-stiftung.ch',
    applicationMethod: 'email',
    contact: {
      email: 'kontakt@hirschmann-stiftung.ch',
    },
    sdgs: [3, 4, 8],
    themes: ['soziale-integration', 'arbeitsintegration', 'digitale-bildung'],
    source: 'robert',
    researchDate: '2026-02-06',
  },
  {
    slug: 'drosos',
    name: 'Drosos Stiftung',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Jederzeit',
    responseTime: '6-12 Monate (inkl. Due Diligence)',
    amount: { min: 50000, max: 500000, text: "CHF 50'000 - 500'000+ (3-5 Jahre)" },
    fit: 2,
    priority: 2,
    tagline: 'Erm\u00F6glicht benachteiligten Menschen, ihr Leben selbst zu gestalten',
    region: 'Z\u00FCrich / Schweiz',
    applicationUrl: 'https://www.drosos.org/how-we-work/partner-us',
    websiteUrl: 'https://www.drosos.org',
    applicationMethod: 'email',
    contact: {
      email: 'info@drosos.org',
    },
    themes: ['jugend', 'soziale-integration', 'arbeitsintegration'],
    source: 'robert',
    researchDate: '2026-02-06',
  },
  {
    slug: 'hasler',
    name: 'Hasler Stiftung',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Jederzeit',
    responseTime: '~30 Tage (kleine Projekte)',
    amount: { min: 10000, max: 50000, text: "CHF 10'000 - 50'000+" },
    smallProjects: { max: 10000, text: "bis CHF 10'000 (Events, Publikationen)" },
    fit: 2,
    priority: 2,
    tagline: 'Die ICT-Stiftung der Schweiz seit 1948',
    founded: 1948,
    region: 'Schweiz',
    applicationUrl: 'https://haslerstiftung.ch/en/what-the-hasler-foundation-supports/supportprograms/',
    websiteUrl: 'https://haslerstiftung.ch',
    applicationMethod: 'online',
    themes: ['digitale-bildung', 'digitale-souveraenitaet', 'jugend'],
    source: 'manual',
    researchDate: '2026-02-06',
  },
  {
    slug: 'zkb-philanthropie',
    name: 'ZKB Philanthropie Stiftung',
    type: 'D',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Jederzeit',
    amount: { min: null, max: null, text: 'Variabel' },
    fit: 2,
    priority: 2,
    tagline: 'Neue Z\u00FCrcher Stiftung - regional verankert',
    founded: 2024,
    region: 'Kanton Z\u00FCrich',
    applicationUrl: 'https://www.zkb-philanthropie-stiftung.ch/de.html',
    websiteUrl: 'https://www.zkb-philanthropie-stiftung.ch',
    applicationMethod: 'online',
    themes: ['zuerich', 'soziale-integration', 'klima', 'digitale-bildung'],
    source: 'manual',
    researchDate: '2026-02-06',
  },
  {
    slug: 'arbeitsintegration-zh',
    name: 'Arbeitsintegration Z\u00FCrich',
    type: 'D',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Jederzeit',
    amount: { min: null, max: null, text: 'Partnerschaft (Lohnkosten \u00FCbernommen)' },
    fit: 3,
    priority: 2,
    tagline: 'Partnerschaft statt Grant - nachhaltiges Einkommen',
    region: 'Stadt Z\u00FCrich',
    applicationUrl: 'https://www.stadt-zuerich.ch/de/lebenslagen/unterstuetzung-und-beratung/arbeitslosigkeit/arbeitsintegration.html',
    websiteUrl: 'https://www.stadt-zuerich.ch/sd/de/index/unterstuetzung/ai/arbeitsintegrationsozialhilfe.html',
    applicationMethod: 'contact',
    isPartnership: true,
    themes: ['zuerich', 'arbeitsintegration', 'soziale-integration'],
    source: 'manual',
    researchDate: '2026-02-06',
  },
  {
    slug: 'zuerich-jobs',
    name: 'Stiftung Z\u00FCrich-Jobs',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Jederzeit',
    amount: { min: null, max: null, text: 'Variabel' },
    capital: 'CHF 3.4 Mio.',
    fit: 3,
    priority: 2,
    tagline: 'Stadt + Wirtschaft f\u00FCr Jugend-Arbeitsintegration',
    founded: 2006,
    region: 'Stadt Z\u00FCrich',
    applicationUrl: 'https://stiftungzuerichjobs.ch/',
    websiteUrl: 'https://stiftungzuerichjobs.ch/ueber/',
    applicationMethod: 'contact',
    themes: ['zuerich', 'jugend', 'arbeitsintegration'],
    source: 'manual',
    researchDate: '2026-02-06',
  },
  {
    slug: 'max-kohler',
    name: 'Max Kohler Stiftung',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Jederzeit',
    amount: { min: null, max: null, text: 'Variabel' },
    fit: 2,
    priority: 2,
    tagline: 'Arts for Change - Kreativit\u00E4t f\u00FCr Integration',
    founded: 2003,
    region: 'Z\u00FCrich',
    applicationUrl: 'https://www.maxkohler-stiftung.ch/en/contact/applications/',
    websiteUrl: 'https://www.maxkohler-stiftung.ch',
    applicationMethod: 'email',
    contact: {
      address: 'Schiffl\u00E4nde 5, 8001 Z\u00FCrich',
    },
    themes: ['zuerich', 'jugend', 'soziale-integration'],
    source: 'manual',
    researchDate: '2026-02-06',
  },
  {
    slug: 'glueckskette',
    name: 'Gl\u00FCckskette',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Jederzeit',
    amount: { min: null, max: null, text: 'Variabel' },
    fit: 2,
    priority: 2,
    tagline: 'Berufliche + Soziale Integration junger Menschen',
    region: 'Schweiz',
    applicationUrl: 'https://www.glueckskette.ch/sammlungen/berufliche-und-soziale-integration-junger-menschen-in-der-schweiz/',
    websiteUrl: 'https://www.glueckskette.ch',
    applicationMethod: 'online',
    themes: ['jugend', 'soziale-integration', 'arbeitsintegration'],
    source: 'manual',
    researchDate: '2026-02-06',
  },
  {
    slug: 'minerva',
    name: 'Minerva Stiftung',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Jederzeit (Entscheide 4x/Jahr)',
    decisionCycle: 'M\u00E4rz, Juni, September, November',
    amount: { min: null, max: null, text: 'Variabel' },
    fit: 3,
    priority: 2,
    tagline: 'Kreislaufwirtschaft & Jugendbildung (15-25) aus Lugano',
    founded: null,
    region: 'Schweiz (Fokus auch Tessin)',
    applicationUrl: 'https://minerva-stiftung.org/',
    websiteUrl: 'https://minerva-stiftung.org',
    applicationMethod: 'online',
    contact: {
      email: 'info@minerva-stiftung.org',
      phone: '+41 (0)79 945 37 38',
    },
    criteria: {
      nature: 'Messbare Projekte mit Skalierungspotenzial, Kreislaufwirtschaft, Ressourcenschonung',
      education: 'Jugendprogramme 15-25, \u00DCbergang Schule-Beruf, hohe Jugendarbeitslosigkeit',
    },
    themes: ['kreislaufwirtschaft', 'jugend', 'soziale-integration', 'arbeitsintegration'],
    source: 'fundraiso',
    researchDate: '2026-02-06',
  },

  // ---- PRIORITY 3: Watch & Wait ----
  {
    slug: 'prototype-fund',
    name: 'Prototype Fund Schweiz',
    type: 'A',
    status: 'soon',
    deadline: null,
    deadlineText: 'Runde 5: Ende Januar 2026 (8 Wochen Bewerbungsfenster)',
    amount: { min: null, max: 100000, text: "bis CHF 100'000 (6 Monate)" },
    fit: 3,
    priority: 3,
    tagline: 'F\u00F6rdert Open-Source-Projekte f\u00FCr das Gemeinwohl',
    region: 'Schweiz',
    applicationUrl: 'https://prototypefund.opendata.ch/bewerbung/',
    websiteUrl: 'https://prototypefund.opendata.ch',
    applicationMethod: 'online',
    requiresOpenSource: true,
    themes: ['digitale-souveraenitaet', 'klima', 'kreislaufwirtschaft'],
    source: 'manual',
    researchDate: '2026-02-06',
  },
  {
    slug: 'migros-getconnected',
    name: 'Migros "Get connected!"',
    type: 'D',
    status: 'closed',
    deadline: null,
    deadlineText: '2025 Runde abgeschlossen - neue Runde ca. Juni 2026',
    amount: { min: 2000, max: 10000, text: "CHF 2'000 - 10'000" },
    fit: 3,
    priority: 3,
    tagline: 'Digitale Inklusion f\u00FCr Benachteiligte',
    region: 'Schweiz',
    applicationUrl: 'https://engagement.migros.ch/en/culture-percentage/social-affairs/getconnected',
    websiteUrl: 'https://engagement.migros.ch',
    applicationMethod: 'online',
    contact: {
      email: 'isabelle.ruckli@mgb.ch',
    },
    stats2025: "45 Projekte, CHF 362'205",
    themes: ['digitale-bildung', 'soziale-integration'],
    source: 'manual',
    researchDate: '2026-02-06',
  },
  {
    slug: 'klimup',
    name: 'Stadt Z\u00FCrich KlimUp',
    type: 'D',
    status: 'closed',
    deadline: null,
    deadlineText: 'Aktuell geschlossen - 2026 Runde geplant',
    amount: { min: 5000, max: 600000, text: 'NPO: CHF 5k-100k (Projekt) / CHF 60k-600k (Betrieb, 2-4 J.)' },
    fit: 3,
    priority: 3,
    tagline: 'Das Z\u00FCrcher F\u00F6rderprogramm f\u00FCr Kreislaufwirtschaft',
    totalBudget: 'CHF 14 Mio. (+ CHF 3 Mio. f\u00FCr 2026 beantragt)',
    region: 'Stadt Z\u00FCrich',
    applicationUrl: 'https://www.stadt-zuerich.ch/de/umwelt-und-energie/klima/beratung-und-foerderung/klimup.html',
    websiteUrl: 'https://www.stadt-zuerich.ch/de/umwelt-und-energie/klima/beratung-und-foerderung/klimup.html',
    applicationMethod: 'online',
    themes: ['zuerich', 'kreislaufwirtschaft', 'klima'],
    source: 'manual',
    researchDate: '2026-02-06',
  },

  // ---- PRIORITY 3: Research Needed - From ESA Registry ----
  {
    slug: 'stellennetz',
    name: 'Stiftung Stellennetz',
    type: 'B',
    status: 'closed',
    deadline: null,
    deadlineText: 'Keine F\u00F6rdergesuche',
    amount: { min: null, max: null, text: 'Nicht anwendbar' },
    fit: 1,
    priority: 1,
    tagline: 'OPERATIV: Betreibt eigene Programme, vergibt keine F\u00F6rdergelder',
    uid: 'CHE-310.604.106',
    region: 'Z\u00FCrich',
    websiteUrl: 'https://stellennetz-zh.ch/',
    contactEmail: 'info@stellennetz-zh.ch',
    contactPhone: '+41 44 297 91 91',
    applicationMethod: 'none',
    purposeSummary: 'Dienstleistungen im Bereich der Arbeitsintegration, Projekte im Auftrag von \u00F6ffentlichen oder privaten Instanzen. ACHTUNG: Operative Stiftung - vergibt keine F\u00F6rdergelder!',
    themes: ['zuerich', 'arbeitsintegration', 'soziale-integration'],
    source: 'esa',
    researchDate: '2026-02-06',
    needsResearch: false,
    isOperative: true,
  },
  {
    slug: 'climatoor',
    name: 'Stiftung climatoor',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Kontakt aufnehmen',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 2,
    priority: 2,
    tagline: 'Umwelt- & Klimaschutz, Bildung, Wissenschaft',
    uid: 'CHE-298.041.207',
    region: 'Z\u00FCrich',
    websiteUrl: 'https://app.spheriq.ch/organisation/stiftung-climatoor',
    applicationMethod: 'direct',
    purposeSummary: 'F\u00F6rdert Umwelt-/Klimaschutz durch: Projektunterst\u00FCtzung, Wissenschaft/Forschung, Sensibilisierung & Bildung. Keine eigene Website gefunden.',
    themes: ['zuerich', 'klima', 'digitale-bildung'],
    source: 'esa',
    researchDate: '2026-02-06',
    needsResearch: true,
    researchNotes: 'Keine eigene Website. Details auf Spheriq. Kontaktdaten \u00FCber Handelsregister ermitteln und direkt anfragen.',
  },
  {
    slug: 'z43-netzero',
    name: 'Z43 NetZero Stiftung',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Laufend',
    amount: { min: 300000, max: 600000, text: 'USD 300-600k/Jahr (gesamt)' },
    fit: 2,
    priority: 2,
    tagline: 'Klimaneutrale Technologien & Forschung',
    uid: 'CHE-281.354.514',
    region: 'Z\u00FCrich / International',
    websiteUrl: 'https://www.fundraiso.ch/en/organisations/z43-netzero-stiftung',
    contactEmail: 'info@z43netzero.org',
    applicationMethod: 'direct',
    purposeSummary: 'Investiert in F&E f\u00FCr skalierbare, klimaneutrale Technologien. Gegr\u00FCndet Aug 2024 durch SPEAG/IT\'IS Foundation. Fokus auf technologische Innovation.',
    themes: ['zuerich', 'klima'],
    source: 'esa',
    researchDate: '2026-02-06',
    needsResearch: false,
    researchNotes: 'Neu gegr\u00FCndet (Aug 2024). Finanziert durch Z43-Geb\u00E4ude E-Fuel Differenz. Stiftungsrat: Prof. Niels Kuster, Dr. Roland Walthert, Dr. Davnah Urbach. Fokus auf technologische R&D - weniger passend f\u00FCr soziale Projekte.',
  },
  {
    slug: 'stopp-klimakrise',
    name: 'Stiftung Stopp Klimakrise - Kurt De Lorenzo',
    type: 'C',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Pers\u00F6nlicher Kontakt',
    amount: { min: null, max: null, text: 'Unbekannt (klein)' },
    fit: 2,
    priority: 2,
    tagline: 'Natur- und Klimaschutz, Ressourcenschonung - KLEINE STIFTUNG',
    uid: 'CHE-391.558.817',
    region: 'Z\u00FCrich',
    websiteUrl: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE391558817&directLink=true',
    applicationMethod: 'personal',
    purposeSummary: 'F\u00F6rdert Natur-/Klimaschutz und Ressourcenschonung. Kleine Familienstiftung ohne Web-Pr\u00E4senz. Pers\u00F6nlicher Kontakt zum Stifter erforderlich.',
    themes: ['zuerich', 'klima', 'kreislaufwirtschaft'],
    source: 'esa',
    researchDate: '2026-02-06',
    needsResearch: true,
    researchNotes: 'Keine Website gefunden. Typ C Familienstiftung - emotionale Entscheide, pers\u00F6nlicher Zugang wichtig. Stifter Kurt De Lorenzo \u00FCber Netzwerk kontaktieren.',
  },
  {
    slug: 'familie-schwarz',
    name: 'Familie Schwarz Stiftung',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Laufend (Kontakt aufnehmen)',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 3,
    priority: 3,
    tagline: 'Umweltschutz, soziale Not, Jugend - GUTER FIT!',
    uid: 'CHE-466.408.960',
    region: 'Z\u00FCrich / Weltweit',
    websiteUrl: 'https://www.fundraiso.ch/sponsor/familie-schwarz-stiftung',
    applicationMethod: 'direct',
    purposeSummary: 'Finanziert: Umweltschutzprojekte, Hilfe f\u00FCr Menschen in sozialer/k\u00F6rperlicher Not, Jugend- und Alterspflege, Gesundheitswesen, Wohnsicherheit. Gegr\u00FCndet Dez 2022.',
    themes: ['zuerich', 'kreislaufwirtschaft', 'klima', 'jugend', 'soziale-integration'],
    source: 'esa',
    researchDate: '2026-02-06',
    needsResearch: false,
    researchNotes: 'Familienstiftung Schwarz, Feldblumenstrasse 19a, 8048 Z\u00FCrich. Stiftungsrat: Konrad Schwarz (Pr\u00E4sident), Alexander Troschel, Barbara Schwarz. Breit aufgestellt: Umwelt + Soziales. Guter Fit f\u00FCr Revamp-IT.',
  },
  {
    slug: 'baitella-eberle',
    name: 'Baitella-Eberle Stiftung',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Laufend (Kontakt aufnehmen)',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 3,
    priority: 3,
    tagline: 'Zukunftstechnologien, Innovation, Umwelt, benachteiligte Jugend - SUPER FIT!',
    uid: 'CHE-389.062.085',
    region: 'Z\u00FCrich / CH / Entwicklungsl\u00E4nder',
    websiteUrl: 'https://www.fundraiso.ch/de/organisations/baitella-eberle-stiftung',
    applicationMethod: 'direct',
    purposeSummary: 'F\u00F6rdert: 1) Aus-/Weiterbildung in Zukunftstechnologien, 2) Innovative Ideen f\u00FCr Allgemeinheit & Umwelt, 3) Bildung f\u00FCr benachteiligte Kinder/Jugendliche, 4) Natur-/Umweltschutz. Gegr\u00FCndet 2024.',
    themes: ['zuerich', 'digitale-bildung', 'klima', 'jugend', 'soziale-integration'],
    source: 'esa',
    researchDate: '2026-02-06',
    needsResearch: false,
    researchNotes: 'Administriert via Z\u00FCrcher Kantonalbank, Bahnhofstrasse 9. Neue Stiftung (2024) mit breitem Fokus. Alle Revamp-IT Kernthemen abgedeckt: Technologie, Umwelt, Bildung, benachteiligte Jugend. HOHE PRIORIT\u00C4T!',
  },
  {
    slug: 'foundation-regina',
    name: 'Foundation Regina',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Laufend (via Hochschule)',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 2,
    priority: 2,
    tagline: 'Informatik & Umweltschutz - AKADEMISCHER FOKUS',
    uid: 'CHE-449.768.771',
    region: 'Z\u00FCrich / International',
    websiteUrl: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE449768771&directLink=true',
    applicationMethod: 'via_partner',
    purposeSummary: 'F\u00F6rdert Forschung in Energie, Technologie, Informatik & Umweltschutz. Prim\u00E4r an Hochschulen/Fachhochschulen. Gegr\u00FCndet 2024. F\u00FCr Revamp-IT: Kooperation mit ZHAW/BFH k\u00F6nnte T\u00FCren \u00F6ffnen.',
    themes: ['zuerich', 'digitale-bildung', 'digitale-souveraenitaet', 'klima'],
    source: 'esa',
    researchDate: '2026-02-06',
    needsResearch: false,
    researchNotes: 'Administriert via STAIGER Rechtsanw\u00E4lte, Talacker 41, 8001 Z\u00FCrich. Keine eigene Website. Fokus auf akademische Forschung - direkter Antrag wahrscheinlich nicht m\u00F6glich, aber \u00FCber Hochschulpartner (ZHAW, BFH) denkbar.',
  },
  {
    slug: 'futuri',
    name: 'Stiftung Futuri',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Direkte Anfrage',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 3,
    priority: 2,
    tagline: 'Ausbildung, berufliche & soziale Integration, Nachhaltigkeit - KONTAKT AUFNEHMEN',
    uid: 'CHE-325.640.105',
    region: 'Z\u00FCrich',
    websiteUrl: 'https://www.futuri.ch/',
    applicationMethod: 'direct',
    purposeSummary: 'F\u00F6rderung von Menschen durch Ausbildung und berufliche/soziale Integration. Betreibt prim\u00E4r eigene Programme f\u00FCr Gefl\u00FCchtete, kann aber auch externe Projekte unterst\u00FCtzen. Direkten Kontakt aufnehmen!',
    themes: ['zuerich', 'arbeitsintegration', 'soziale-integration', 'jugend', 'klima'],
    source: 'esa',
    researchDate: '2026-02-06',
    needsResearch: false,
    researchNotes: 'Prim\u00E4r operative Stiftung (eigene Ausbildungsprogramme), aber laut Zweck auch F\u00F6rderung von externen Projekten m\u00F6glich. Direktkontakt empfohlen.',
  },
  {
    slug: 'erde-2-0',
    name: 'ERDE 2.0 Stiftung',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Laufend (akademisch)',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 2,
    priority: 2,
    tagline: 'Klimaresilienz & Technologie - AKADEMISCHER FOKUS',
    uid: 'CHE-443.701.461',
    region: 'Z\u00FCrich / CH / International',
    websiteUrl: 'https://stiftungen.stiftungschweiz.ch/organisation/erde-2-0-stiftung',
    applicationMethod: 'via_partner',
    purposeSummary: 'F\u00F6rdert wissenschaftliche Ideen f\u00FCr Klimaresilienz: Klima/Wetter, Energie/Wasser/Nahrung, Gesundheit, technologische Innovation. Prim\u00E4r akademische Initiativen mit CH-Institutionen.',
    themes: ['zuerich', 'klima', 'digitale-bildung'],
    source: 'esa',
    researchDate: '2026-02-06',
    needsResearch: false,
    researchNotes: 'Administriert via Centralis Switzerland, Kanzleistrasse 18, 8004 Z\u00FCrich. Starker akademischer Fokus. F\u00FCr Revamp-IT evtl. \u00FCber Hochschulpartner (ZHAW, BFH) - z.B. f\u00FCr Impact-Studie zu IT-Refurbishing.',
  },
  {
    slug: 'responsability',
    name: 'responsAbility Foundation',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Wahrscheinlich nicht passend',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 1,
    priority: 1,
    tagline: 'UN SDGs, Entwicklungsl\u00E4nder - NICHT F\u00DCR CH-PROJEKTE',
    uid: 'CHE-389.004.225',
    region: 'Entwicklungsl\u00E4nder',
    websiteUrl: 'https://zh.chregister.ch/cr-portal/auszug/auszug.xhtml?uid=CHE-389.004.225',
    applicationMethod: 'unknown',
    purposeSummary: 'Beitrag zu UN-SDGs durch Impact Investing in Entwicklungs-/Schwellenl\u00E4nder. ESG-fokussiert. Katalytisches Kapital. Gegr\u00FCndet 2024.',
    themes: ['klima', 'soziale-integration'],
    source: 'esa',
    researchDate: '2026-02-06',
    needsResearch: false,
    researchNotes: 'Verkn\u00FCpft mit responsAbility Investments AG (Impact Investing). Fokus auf Entwicklungsl\u00E4nder - nicht f\u00FCr Schweizer Projekte wie Revamp-IT geeignet, ausser wir expandieren international.',
  },
  {
    slug: 'landscape-resilience',
    name: 'Landscape Resilience Fund',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Nicht f\u00FCr CH-Projekte',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 1,
    priority: 1,
    tagline: 'Klimaanpassung, Entwicklungsl\u00E4nder - NICHT F\u00DCR CH-PROJEKTE',
    uid: 'CHE-485.173.674',
    region: 'Entwicklungsl\u00E4nder',
    websiteUrl: 'https://www.zefix.admin.ch/de/search/entity/list?name=CHE485173674&directLink=true',
    applicationMethod: 'unknown',
    purposeSummary: "Klimaanpassung und KMU-Finanzierung in Schwellen- und Entwicklungsl\u00E4ndern. Landschaftsansatz ('landscape approach'). Gegr\u00FCndet 2021.",
    themes: ['klima'],
    source: 'esa',
    researchDate: '2026-02-06',
    needsResearch: false,
    researchNotes: 'Expliziter Fokus auf Entwicklungs- und Schwellenl\u00E4nder. Nicht f\u00FCr Schweizer Projekte wie Revamp-IT geeignet.',
  },
  {
    slug: 'rethink',
    name: 'Stiftung Rethink!',
    type: 'C',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Partnerschaft anfragen',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 3,
    priority: 2,
    tagline: 'Repair Centers, Secondhand Centers - POTENTIELLER PARTNER!',
    uid: 'CHE-190.533.848',
    region: 'Aarau / CH',
    websiteUrl: 'https://www.fundraiso.com/en/organisations/stiftung-rethink',
    applicationMethod: 'partnership',
    purposeSummary: "Will 'Wegwerfgesellschaft' beenden durch Repair Centers, Secondhand Centers, Rental Centers. Basiert auf Buch 'RETHINK THE WORLD'. Gegr\u00FCndet 2023.",
    themes: ['kreislaufwirtschaft', 'klima'],
    source: 'esa',
    researchDate: '2026-02-06',
    needsResearch: true,
    researchNotes: 'SEHR RELEVANT! Gleiche Vision wie Revamp-IT. Eher Partnerschaft als F\u00F6rderung? Kontakt aufnehmen f\u00FCr Zusammenarbeit bei Repair/Secondhand-Projekten. Adresse: Aarestrasse 38, 5000 Aarau.',
  },
  {
    slug: 'globility-circle',
    name: 'Stiftung Globility Circle',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Laufend',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 2,
    priority: 2,
    tagline: 'Soziales Unternehmertum, \u00F6kologischer Fortschritt',
    uid: 'CHE-114.571.634',
    region: 'Luzern / CH',
    websiteUrl: 'https://globility-circle.org/',
    applicationMethod: 'direct',
    purposeSummary: "F\u00F6rdert soziales Unternehmertum durch ideelle, fachliche und finanzielle Unterst\u00FCtzung. 'Global denken - regional handeln'. Gegr\u00FCndet 2008.",
    themes: ['soziale-integration', 'klima'],
    source: 'esa',
    researchDate: '2026-02-06',
    needsResearch: true,
    researchNotes: 'Fokus auf Social Entrepreneurship. K\u00F6nnte Revamp-IT als Sozialunternehmen f\u00F6rdern. Website hat keine klaren F\u00F6rderkriterien - direkt anfragen.',
  },
  {
    slug: 'fair-recycling',
    name: 'Stiftung Fair Recycling',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'International fokussiert',
    amount: { min: null, max: null, text: 'Unbekannt' },
    fit: 1,
    priority: 1,
    tagline: 'E-Waste Recycling - INTERNATIONALE PROJEKTE',
    uid: 'CHE-114.639.568',
    region: 'International (nicht CH)',
    websiteUrl: 'https://stiftungen.stiftungschweiz.ch/organisation/stiftung-fair-recycling',
    applicationMethod: 'unknown',
    purposeSummary: 'Elektroschrott-Recycling in Entwicklungs- und Schwellenl\u00E4ndern. Gegr\u00FCndet 2008 durch SENS eRecycling. Fokus auf internationale Projekte.',
    themes: ['kreislaufwirtschaft', 'klima'],
    source: 'esa',
    researchDate: '2026-02-06',
    needsResearch: false,
    researchNotes: 'Fokus auf internationale E-Waste Projekte (nicht Schweiz). Kontakt: Dr. Andreas R\u00F6thlisberger, Kirschgarten 13, 5000 Aarau. F\u00FCr Revamp-IT weniger relevant ausser bei internationaler Expansion.',
  },
  {
    slug: 'wirtschaft-gesellschaft',
    name: 'Stiftung f\u00FCr Wirtschaft und Gesellschaft',
    type: 'B',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Laufend',
    amount: { min: null, max: null, text: 'Darlehen/Beteiligung' },
    fit: 3,
    priority: 3,
    tagline: 'Nachhaltiges Unternehmertum, KMU, Arbeitspl\u00E4tze - SEHR RELEVANT!',
    uid: 'CHE-344.116.046',
    region: 'Heimberg / CH',
    websiteUrl: 'https://app.spheriq.ch/organisation/stiftung-fuer-wirtschaft-und-gesellschaft',
    applicationMethod: 'direct',
    purposeSummary: 'F\u00F6rdert verantwortungsvolles KMU-Unternehmertum. Schaffung von Arbeitspl\u00E4tzen, auch f\u00FCr Personen mit eingeschr\u00E4nkter Leistungsf\u00E4higkeit. Darlehen, Kapitalbeteiligung, Coaching.',
    themes: ['soziale-integration', 'arbeitsintegration'],
    source: 'esa',
    researchDate: '2026-02-06',
    needsResearch: true,
    researchNotes: 'Gegr\u00FCndet 2014 in Heimberg. SEHR RELEVANT: Explizit Arbeitspl\u00E4tze f\u00FCr Personen mit eingeschr\u00E4nkter Leistungsf\u00E4higkeit genannt! Bietet Darlehen, Kapitalbeteiligung UND Coaching. Kein eigenes Website.',
  },
  {
    slug: 'svc-unternehmertum',
    name: 'SVC Stiftung f\u00FCr das Unternehmertum',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Laufend',
    amount: { min: null, max: null, text: 'Projektf\u00F6rderung' },
    fit: 2,
    priority: 2,
    tagline: 'KMU-F\u00F6rderung, Unternehmertum, Bildung',
    uid: 'CHE-217.027.356',
    region: 'G\u00FCmligen / CH',
    websiteUrl: 'https://svc-stiftung.swiss/',
    contactEmail: 'svc.stiftung@svc.swiss',
    contactPhone: '+41 31 358 72 72',
    applicationMethod: 'direct',
    purposeSummary: 'F\u00F6rdert Unternehmertum und KMU in allen Regionen der Schweiz. Bildungsmassnahmen f\u00FCr unternehmerische Kompetenzen. Gegr\u00FCndet 2010 aus Swiss Venture Club.',
    themes: ['digitale-bildung'],
    source: 'esa',
    researchDate: '2026-02-06',
    needsResearch: false,
    researchNotes: 'Teil von Swiss Venture Club. Website: svc-stiftung.swiss. Fokus auf Entrepreneurship-Bildung. Adresse: Worbstrasse 187, 3073 G\u00FCmligen.',
  },

  // ---- Networks & Resources (not direct funders) ----
  {
    slug: 'netzwerk-sds',
    name: 'Netzwerk SDS',
    type: 'network',
    status: 'open',
    deadline: null,
    deadlineText: 'Mitgliedschaft jederzeit',
    amount: { min: null, max: null, text: 'Netzwerk (keine direkte F\u00F6rderung)' },
    fit: 2,
    priority: 4,
    tagline: 'Souver\u00E4ne Digitale Schweiz',
    members: '100+ Organisationen',
    region: 'Schweiz',
    applicationUrl: 'https://netzwerksds.ch/',
    websiteUrl: 'https://netzwerksds.ch',
    applicationMethod: 'membership',
    partners: ['BFH', 'EJPD', 'Stadt Z\u00FCrich', 'Post', 'SWITCH'],
    isNetwork: true,
    themes: ['digitale-souveraenitaet'],
    source: 'manual',
    researchDate: '2026-02-06',
  },
  {
    slug: 'ch-open',
    name: 'CH Open',
    type: 'network',
    status: 'open',
    deadline: null,
    deadlineText: 'Mitgliedschaft jederzeit',
    amount: { min: null, max: null, text: 'CHF ~200/Jahr (Verein)' },
    fit: 2,
    priority: 4,
    tagline: 'Open Source Community seit 1982',
    members: '~200 Personen, 54 Kollektiv, 53 Sponsoren',
    region: 'Schweiz',
    applicationUrl: 'https://www.ch-open.ch/en/',
    websiteUrl: 'https://www.ch-open.ch',
    applicationMethod: 'membership',
    events: ['DINAcon', 'Lunch Lectures'],
    isNetwork: true,
    themes: ['digitale-souveraenitaet'],
    source: 'manual',
    researchDate: '2026-02-06',
  },
  {
    slug: 'innosuisse',
    name: 'Innosuisse',
    type: 'A',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Jederzeit (mit Forschungspartner)',
    amount: { min: null, max: null, text: 'Variabel (substanziell)' },
    fit: 1,
    priority: 4,
    tagline: 'F\u00F6rderagentur f\u00FCr Innovation',
    region: 'Schweiz',
    applicationUrl: 'https://www.innosuisse.admin.ch/en/foerderangebote',
    websiteUrl: 'https://www.innosuisse.admin.ch',
    applicationMethod: 'partnership',
    requiresPartner: true,
    possiblePartners: ['BFH', 'ZHAW', 'Empa'],
    themes: ['kreislaufwirtschaft', 'digitale-souveraenitaet'],
    source: 'manual',
    researchDate: '2026-02-06',
  },
  {
    slug: 'swico',
    name: 'Swico Innovationsfonds',
    type: 'D',
    status: 'rolling',
    deadline: null,
    deadlineText: 'Jederzeit (Swico-Vertrag erforderlich)',
    amount: { min: null, max: 300000, text: "bis CHF 300'000" },
    fit: 1,
    priority: 4,
    tagline: "Bis CHF 300k f\u00FCr IT-Recycling-Projekte",
    region: 'Schweiz',
    applicationUrl: 'https://www.swico.ch/de/recycling/innovationsfonds/',
    websiteUrl: 'https://www.swico.ch/de/recycling/innovationsfonds/wer-kann-sich-bewerben/',
    applicationMethod: 'contract',
    requiresContract: true,
    themes: ['kreislaufwirtschaft'],
    source: 'manual',
    researchDate: '2026-02-06',
  },
] satisfies Foundation[];

// ============================================================================
// NOT RECOMMENDED - Foundations that don't fit Revamp-IT
// ============================================================================

export const NOT_RECOMMENDED = [
  { name: 'Avina Stiftung', reason: 'Nur Ern\u00E4hrung/Food - "Soziale Projekte" explizit ausgeschlossen' },
  { name: 'Gebert R\u00FCf Stiftung', reason: 'Nur Uni-Spin-offs und Hochschulprojekte' },
  { name: 'Velux Stiftung', reason: 'Nur akademische Forschung (Tageslicht, Wald, Alter)' },
  { name: 'Stiftung Walder', reason: 'Nur Projekte f\u00FCr Senioren (65+)' },
  { name: 'Pestalozzi-Stiftung', reason: 'F\u00FChrt eigene Programme, keine externe F\u00F6rderung' },
  { name: 'UBS Optimus Foundation', reason: 'Aktuell geschlossen f\u00FCr Bewerbungen, globaler Fokus' },
  { name: 'Swiss Re Foundation', reason: 'Nur Entwicklungsl\u00E4nder' },
  { name: 'Coop Nachhaltigkeitsfonds', reason: 'Stark auf Food fokussiert, "Kerngesch\u00E4ft-Verbindung" n\u00F6tig' },
] as const;

// ============================================================================
// FOUNDATION DATABASES - For finding more foundations
// ============================================================================

export const DATABASES = [
  {
    name: 'Fundraiso.ch',
    url: 'https://www.fundraiso.ch/de/page/stiftungsverzeichnis-schweiz',
    count: "13'300+",
    cost: 'Basis: Gratis / Pro: Abo',
    description: 'T\u00E4glich aktualisierte Datenbank aller gemeinn\u00FCtzigen Stiftungen der Schweiz',
  },
  {
    name: 'StiftungSchweiz',
    url: 'https://stiftungen.stiftungschweiz.ch/',
    count: "~14'000",
    cost: 'Basis: Gratis / Premium: Abo',
    description: 'Umfassende Plattform mit erweiterten Filteroptionen: Wirkungsart, Themengebiet, Zielgruppe, SDGs',
  },
  {
    name: 'Eidg. Stiftungsaufsicht',
    url: 'https://www.esa.admin.ch/de/stiftungsverzeichnis',
    count: 'Variabel',
    cost: 'Gratis',
    description: 'Offizielles Register der Stiftungen unter Bundesaufsicht',
  },
] as const;

// ============================================================================
// TYPE LABELS (Robert Schmuki classification)
// ============================================================================

export const TYPE_LABELS: Record<FoundationType, TypeLabel> = {
  A: {
    short: 'A',
    long: 'Professionalisierte F\u00F6rderstiftung',
    desc: 'Professionelles Management, Entscheide basieren auf Analysen & Normen',
    approach: 'Strukturierte Antr\u00E4ge, Impact-Metriken, professionelle Kommunikation',
  },
  B: {
    short: 'B',
    long: 'Potente Familienstiftung',
    desc: 'Familienstiftung mit Administration, pers\u00F6nliche Interessen relevant',
    approach: 'Pers\u00F6nliche Beziehung aufbauen, Story erz\u00E4hlen, Werte teilen',
  },
  C: {
    short: 'C',
    long: 'Kleine Familienstiftung',
    desc: 'Kleines Gremium (3-5 Personen), emotionale Entscheide, direkte Bewerbung',
    approach: 'Direkter Kontakt, emotionaler Appeal, kurze pr\u00E4gnante Anfrage',
  },
  D: {
    short: 'D',
    long: 'Corporate Foundation',
    desc: 'Professionell aber weniger transparent, normbasierte Prozesse',
    approach: 'Alignment mit Unternehmenszielen zeigen, CSR-Sprache verwenden',
  },
  network: {
    short: 'N',
    long: 'Netzwerk',
    desc: 'Netzwerk/Verband - keine direkte F\u00F6rderung',
    approach: 'Mitgliedschaft f\u00FCr Sichtbarkeit und Partnerschaften',
  },
} as const satisfies Record<FoundationType, TypeLabel>;

// ============================================================================
// STATUS LABELS
// ============================================================================

export const STATUS_LABELS: Record<FoundationStatus, StatusLabel> = {
  open: { text: 'Offen', class: 'open', desc: 'Bewerbungen werden angenommen' },
  closed: { text: 'Geschlossen', class: 'closed', desc: 'Aktuell keine Bewerbungen m\u00F6glich' },
  soon: { text: '\u00D6ffnet bald', class: 'soon', desc: 'Bewerbungsportal \u00F6ffnet demn\u00E4chst' },
  rolling: { text: 'Laufend', class: 'rolling', desc: 'Jederzeit bewerbbar' },
} as const satisfies Record<FoundationStatus, StatusLabel>;
