// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Source: org_numbers table (Neon PostgreSQL)
// Last synced: 2026-02-16
// Run: npm run sync-numbers

export const SHARED_ORG_NUMBERS = {
  CO2_SAVED_PER_LAPTOP: 285,
  REUSE_RATE: 75,
  DEVICE_LIFESPAN_EXTENSION: 5,
  PEOPLE_HELPED: '100+',
  FOUNDING_YEAR: 2003,
  CURRENT_BUDGET: 60000,
  TEAM_CORE_FTE: 3,
  AVG_DEVICE_PRICE: 150,
  DEVICES_YEAR_CURRENT: 150,
} as const
